#!/usr/bin/env python3
"""The season gate: fresh files, pinned totals, and a date policy that does what it says.

    tests/season/check.py                                   everything that needs no raw inputs
    SEASON_CAPTURE=<capture folder> tests/season/check.py   and a regeneration from the raw inputs
    tests/season/check.py <word>                            only the tests whose name has the word

Three tiers. The first two run anywhere.

1. THE COMMITTED FILES. data/season/ is generated by pipeline/season.py from raw copies that
   run to megabytes and are deliberately not in this repository. So the freshness check
   rebuilds everything that CAN be rebuilt from committed files (every derived field of every
   fire, the summary, the day index, the provenance record, the snapshot day) and compares
   bytes. Then every published number is worked out a second time, by code written here and
   not shared with the generator: a generator checked only against itself proves nothing
   about its arithmetic. PINS below are the totals a reader will see published, and two
   fingerprints of the values that came straight from the raw inputs. They move only when
   somebody moves them. The documents that quote the numbers are held to the same data.

2. A SYNTHETIC SEASON. Sixteen invented fires, a recovered mirror history, a snapshot and
   three captures are written to scratch and run through the real generator. Every flag, both
   placement rules, the last copy of a local day across a UTC midnight, the status filter,
   --through, and every refusal are asserted there, on inputs small enough to check by hand.

3. THE RAW INPUTS. With SEASON_CAPTURE set, the season is regenerated from the capture and
   must match the committed files byte for byte, and the perimeter generalisation is held
   against every perimeter the server itself generalised. Without it those tests SKIP, loudly,
   naming the folders they need. They never pass quietly.

Exit status is non-zero on any failure. A skip is not a failure and is never silent.
Python 3 and its standard library; no browser, no node, no network.
"""
import ast
import datetime
import hashlib
import json
import os
import pathlib
import re
import shutil
import socket
import sys
import tempfile
import urllib.parse

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / "pipeline"))
import season  # noqa: E402  (the generator under test)

SEASON = ROOT / "data" / "season"

# ---- the pins: what a reader will see published --------------------------------------------
# Adding a status day moves statusDays and dayFilesSha256 and nothing else here. Re-pinning
# the season to a later capture moves nearly all of them. Either way they are changed in this
# file, by hand, in the commit that changes the data, and the commit says why.
YEAR = 2026
PINS = {
    "total": 1439,
    "statusTally": {"Being Held": 13, "Out": 1353, "Out of Control": 1, "Under Control": 72},
    # status day: fires listed that day
    "statusDays": {"2026-08-08": 105, "2026-08-09": 103, "2026-08-10": 101, "2026-08-11": 103,
                   "2026-08-12": 109, "2026-08-13": 107, "2026-08-14": 121, "2026-08-15": 131,
                   "2026-09-20": 96, "2026-09-22": 103, "2026-10-01": 86},
    # fire: IGNITION_DATE and FIRE_OUT_DATE exactly as published (epoch milliseconds, UTC),
    # and the fire's timeline date if a rule places it
    "impossible": {
        "G90400": (1747765892000, 1786803721000, None),
        "V10408": (-2208963600000, 1780073080000, None),
        "G40517": (1759358114000, 1780866289000, None),
        "V10591": (1781899200000, 1781897642000, "2026-06-19"),
        "C30602": (2366768820000, 1782064294000, None),
        "V30852": (1752619213000, 1786735367000, "2026-07-15"),
        "C20940": (-17041510053000, 1784753884000, None),
        "K61758": (1790093545000, None, None),
        "K41895": (998463600000, 1787614211000, None),
        "N52060": (1790531100000, 1788728221000, None),
    },
    "under1ha": 1144,
    "medianDaysIgnitionToOut": 2.22,
    "peak": {"active": 244, "dates": ["2026-08-23"]},
    "byCause": {"Lightning": 895, "Person": 505, "Unknown": 39},
    "byCentre": {"Cariboo": 231, "Coastal": 325, "Kamloops": 324, "Northwest": 53,
                 "Prince George": 162, "Southeast": 344},
    # The raw inputs, by fingerprint: the capture's manifest, the values each fire's record
    # took from the capture, and the status-day files. These make "the pinned inputs" a phrase
    # that can be checked on a machine that does not have them.
    "captureManifestSha256": "0545dd49269aab70af6b57232b6038329e1198be40b5a537ed8bf0b284634842",
    "recordsSha256": "3d25125d372b31709ec14ad913645c2e2c08856a1c959078b076190fc8424992",
    "dayFilesSha256": "9e523a0f0844de2f46b082d36ef5adbf13347d30508370fa20da013dc14c9a9c",
    # Facts only the raw inputs can show. Checked when SEASON_CAPTURE is set.
    "generalisation": {"mirrorHistory": 97, "snapshot": 24},
    "everyDatedRecord": {"fires": 251, "inSeasonFile": 249,
                         "notInSeasonFile": ["R11561", "V81619"], "seasonFiresInNone": 1190},
}

RECORD_KEYS = ["fire", "name", "place", "lat", "lon", "centre", "cause", "ignited", "out",
               "statusAtCapture", "fireOfNote", "wasFireOfNote", "hindsightSizeHa", "ignitionMs",
               "outMs", "dates"]
AS_PUBLISHED = ["fire", "name", "place", "lat", "lon", "centre", "cause", "statusAtCapture",
                "fireOfNote", "wasFireOfNote", "hindsightSizeHa", "ignitionMs", "outMs"]
LETTERS = {"C": "Cariboo", "V": "Coastal", "K": "Kamloops", "R": "Northwest",
           "G": "Prince George", "N": "Southeast"}
MONTHS = ["", "January", "February", "March", "April", "May", "June", "July", "August",
          "September", "October", "November", "December"]
NUMBER_WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
                "ten", "eleven", "twelve"]
VANCOUVER = season.ZONE      # one zone object; the arithmetic on it below is this file's own

TESTS = []


class Skip(Exception):
    pass


def test(fn):
    TESTS.append(fn)
    return fn


def same(got, want, what):
    assert got == want, f"{what}: got {got!r}, expected {want!r}"


def raises(fn, fragment):
    try:
        fn()
    except season.SeasonError as e:
        assert fragment in str(e), f"refused for the wrong reason: {e}"
        return str(e)
    raise AssertionError(f"was not refused; expected an error mentioning {fragment!r}")


def load(name):
    return json.loads((SEASON / name).read_bytes())


def local_day(ms):
    """This file's own conversion of an instant to its Vancouver date, not the generator's."""
    d = datetime.datetime.fromtimestamp(ms / 1000, tz=datetime.timezone.utc)
    return d.astimezone(VANCOUVER).strftime("%Y-%m-%d")


def count(values):
    """How many of each. A missing value is counted under 'null', as the files publish it."""
    out = {}
    for v in values:
        key = "null" if v is None else v
        out[key] = out.get(key, 0) + 1
    return out


def median(values):
    values = sorted(values)
    mid = len(values) // 2
    return values[mid] if len(values) % 2 else (values[mid - 1] + values[mid]) / 2


def fingerprint(fires):
    """The season record with everything derived stripped out: what the capture itself said."""
    rows = [[f[k] for k in AS_PUBLISHED] for f in fires]
    return hashlib.sha256(json.dumps(rows, separators=(",", ":")).encode()).hexdigest()


def day_fingerprint(index, folder=SEASON):
    lines = []
    for d in index["days"]:
        for name in ("fires", "perims"):
            data = (folder / d[name]["file"]).read_bytes()
            lines.append(f"{d[name]['file']} {hashlib.sha256(data).hexdigest()}")
    return hashlib.sha256("\n".join(lines).encode()).hexdigest()


def squeeze(text):
    return " ".join(text.split())


def long_date(iso):
    """2026-10-01 -> '1 October'."""
    return f"{int(iso[8:10])} {MONTHS[int(iso[5:7])]}"


def word(n):
    return NUMBER_WORDS[n] if 0 <= n < len(NUMBER_WORDS) else str(n)


# ============================================================================================
# 1. THE COMMITTED FILES
# ============================================================================================
@test
def committed_files_match_a_regeneration():
    """The freshness gate. No raw inputs: rebuild from what is committed, compare bytes."""
    same(season.committed_years(SEASON), [YEAR], "seasons under data/season/")
    files = season.build(season.read_committed(YEAR, SEASON))
    problems = season.drift(files, YEAR, SEASON)
    assert not problems, "; ".join(problems)
    return f"{len(files)} files rebuilt from committed files, byte for byte"


@test
def pinned_totals_have_not_moved():
    s, summary = load(f"{YEAR}.json"), load(f"{YEAR}.summary.json")
    index = load(f"{YEAR}.days.json")
    same(s["total"], PINS["total"], "total fires")
    same(len(s["fires"]), PINS["total"], "fire records")
    same(len({f["fire"] for f in s["fires"]}), PINS["total"], "distinct fire numbers")
    same(s["statusTally"], PINS["statusTally"], "status tally at capture")
    same(summary["total"], PINS["total"], "summary total")
    same(summary["statusAtCapture"], PINS["statusTally"], "summary status tally")
    days = list(PINS["statusDays"])
    same(index["dates"], days, "status days")
    same({d["date"]: d["fires"]["count"] for d in index["days"]}, PINS["statusDays"],
         "fires listed on each status day")
    same((index["count"], summary["statusDays"]["count"]), (len(days), len(days)), "day counts")
    same(summary["statusDays"]["dates"], days, "summary status days")
    same(s["impossibleDates"]["fires"], len(PINS["impossible"]), "impossible-date count")
    same(summary["impossibleDates"]["fires"], len(PINS["impossible"]), "summary impossible count")
    same(s["capture"]["manifest"]["sha256"], PINS["captureManifestSha256"], "capture manifest")
    same(fingerprint(s["fires"]), PINS["recordsSha256"], "fingerprint of the records as published")
    same(day_fingerprint(index), PINS["dayFilesSha256"], "fingerprint of the status-day files")
    return (f"{s['total']:,} fires, {len(days)} status days, "
            f"{s['impossibleDates']['fires']} impossible dates, two fingerprints")


@test
def published_facts_recomputed_a_second_way():
    """Every number in the summary, worked out again here from the records and the day files."""
    s, summary = load(f"{YEAR}.json"), load(f"{YEAR}.summary.json")
    fires = s["fires"]
    by_number = {f["fire"]: f for f in fires}
    tally = count(f["statusAtCapture"] for f in fires)
    same(tally, summary["statusAtCapture"], "status tally")
    same(sum(1 for f in fires if f["statusAtCapture"] != "Out"), summary["notOutAtCapture"],
         "not out at capture")

    small = [f for f in fires if f["hindsightSizeHa"] is not None and f["hindsightSizeHa"] < 1]
    same({"fires": len(small), "out": sum(1 for f in small if f["statusAtCapture"] == "Out"),
          "notOut": sum(1 for f in small if f["statusAtCapture"] != "Out"),
          "sizeZero": sum(1 for f in fires if f["hindsightSizeHa"] == 0),
          "sizeUnknown": sum(1 for f in fires if f["hindsightSizeHa"] is None)},
         summary["under1ha"], "under 1 ha")
    same(len(small), PINS["under1ha"], "under 1 ha (pin)")

    # the median: exact instants, over the fires that are out and whose dates are possible
    spans = [(f["outMs"] - f["ignitionMs"]) / 86400000 for f in fires
             if f["dates"]["ok"] and f["outMs"] is not None]
    same({"medianDays": round(median(spans), 2), "medianHours": round(median(spans) * 24, 1),
          "fires": len(spans), "outFiresLeftOut": tally["Out"] - len(spans)},
         summary["ignitionToOut"], "ignition to out")
    same(summary["ignitionToOut"]["medianDays"], PINS["medianDaysIgnitionToOut"], "median (pin)")

    for key, field in (("byCause", "cause"), ("byCentre", "centre")):
        same(count(f[field] for f in fires), summary[key], key)
        same(summary[key], PINS[key], f"{key} (pin)")
    for f in fires:                       # the centre name is the number's letter, every time
        same(f["centre"], LETTERS[f["fire"][0]], f"{f['fire']} centre")
    same({"atCapture": sum(1 for f in fires if f["fireOfNote"]),
          "atCaptureOrEarlier": sum(1 for f in fires if f["fireOfNote"] or f["wasFireOfNote"])},
         summary["fireOfNote"], "fires of note")

    # the timeline, by brute force: one question per fire per day
    t = summary["timeline"]
    same(t["to"], s["capture"]["localDate"], "timeline end")
    same(t["from"], min(f["ignited"] for f in fires if f["ignited"]), "timeline start")
    day, last = datetime.date.fromisoformat(t["from"]), datetime.date.fromisoformat(t["to"])
    series = []
    while day <= last:
        d = day.isoformat()
        series.append({
            "date": d,
            "started": sum(1 for f in fires if f["ignited"] == d),
            "out": sum(1 for f in fires if f["out"] == d),
            "active": sum(1 for f in fires if f["ignited"] is not None and f["ignited"] <= d
                          and (f["out"] is None or d < f["out"]))})
        day += datetime.timedelta(days=1)
    same(series, t["days"], "timeline days")
    top = max(x["active"] for x in series)
    same({"active": top, "dates": [x["date"] for x in series if x["active"] == top]}, t["peak"],
         "peak day")
    same(t["peak"], PINS["peak"], "peak day (pin)")
    same(sum(x["started"] for x in series), t["firesOnTimeline"], "fires started on the timeline")
    same(t["firesOnTimeline"] + t["firesNotOnTimeline"], len(fires), "timeline split")
    running = 0
    for x in series:                     # started minus out, accumulated, IS active
        running += x["started"] - x["out"]
        same(running, x["active"], f"running balance on {x['date']}")

    # how closely the numbering follows the calendar
    ok = [datetime.date.fromisoformat(f["ignited"]) for f in fires if f["dates"]["ok"]]
    gaps = [abs((b - a).days) for a, b in zip(ok, ok[1:])]
    same({"firesWithPossibleDates": len(ok), "pairs": len(gaps),
          "ignitedTheSameDay": sum(1 for g in gaps if g == 0),
          "ignitedWithinOneDay": sum(1 for g in gaps if g <= 1),
          "ignitedWithinSevenDays": sum(1 for g in gaps if g <= 7), "largestGapDays": max(gaps)},
         summary["numbering"], "numbering")

    # the status days, recounted from the day files themselves
    listed_ever, first_seen = set(), {}
    for want in summary["statusDays"]["days"]:
        doc = load(f"days/{want['date']}/fires.json")
        props = [f["properties"] for f in doc["data"]["features"]]
        when = season.parse_utc(doc["fetchedAt"])
        same(local_day(when), want["date"], "a status day's local date")
        listed = {p["FIRE_NUMBER"] for p in props}
        listed_ever |= listed
        for p in props:
            first_seen.setdefault(p["FIRE_NUMBER"], p["IGNITION_DATE"])
        burning = {f["fire"] for f in fires if f["dates"]["ok"] and f["ignitionMs"] <= when
                   and (f["outMs"] is None or f["outMs"] > when)}
        got = {
            "date": want["date"], "fetchedAt": doc["fetchedAt"], "fires": len(props),
            "byStatus": count(p["FIRE_STATUS"] for p in props),
            "byCause": count(p["FIRE_CAUSE"] for p in props),
            "byCentre": count(LETTERS[p["FIRE_NUMBER"][0]] for p in props),
            "under1ha": sum(1 for p in props
                            if p["CURRENT_SIZE"] is not None and p["CURRENT_SIZE"] < 1),
            "fireOfNote": sum(1 for p in props if p["FIRE_STATUS"] == "Fire of Note"
                              or p["FIRE_OF_NOTE_IND"] in ("Y", "Yes")),
            "perimeters": len(load(f"days/{want['date']}/perims.json")["data"]["features"]),
            "hindsightAtThatMoment": {
                "burning": len(burning), "alsoListed": len(burning & listed),
                "notListed": len(burning - listed), "listedNotBurning": len(listed - burning)}}
        same(got, want, f"status day {want['date']}")
    same({"firesListedOnAStatusDay": len(listed_ever),
          "ofThemInSeasonFile": len(listed_ever & set(by_number)),
          "ofThemNotInSeasonFile": sorted(listed_ever - set(by_number)),
          "seasonFiresNeverListed": len(set(by_number) - listed_ever)},
         summary["coverage"], "coverage")

    # how far the ignition date moved between a fire's first status day and the capture
    shifts = [(by_number[n]["ignitionMs"] - then, by_number[n]["ignitionMs"], then)
              for n, then in first_seen.items() if n in by_number and then is not None
              and by_number[n]["ignitionMs"] is not None]
    moved = [d for d, _, _ in shifts if d]
    same({"firesCompared": len(shifts), "sameInstant": sum(1 for d, _, _ in shifts if d == 0),
          "earlierAtCapture": sum(1 for d, _, _ in shifts if d < 0),
          "laterAtCapture": sum(1 for d, _, _ in shifts if d > 0),
          "differentLocalDate": sum(1 for _, now, then in shifts
                                    if local_day(now) != local_day(then)),
          "medianShiftHoursWhereMoved": round(median(moved) / 3600000, 1) if moved else None},
         summary["ignitionRevised"], "ignition revised")
    return (f"under 1 ha {len(small):,}; median {round(median(spans), 2)} d over "
            f"{len(spans):,} fires; peak {top} on {', '.join(t['peak']['dates'])}; "
            f"{len(series)} timeline days; {len(summary['statusDays']['days'])} status days")


@test
def impossible_dates_are_kept_counted_flagged_and_not_repaired():
    s, summary = load(f"{YEAR}.json"), load(f"{YEAR}.summary.json")
    cap_ms = season.parse_utc(s["capture"]["capturedAt"])
    flagged = {f["fire"]: f for f in s["fires"] if not f["dates"]["ok"]}
    same(sorted(flagged), sorted(PINS["impossible"]), "the fires with an impossible date")
    table = season.table(s)
    for n, (ig, out, placed) in PINS["impossible"].items():
        f = flagged[n]
        same((f["ignitionMs"], f["outMs"]), (ig, out), f"{n}: the values as published")   # kept
        same(f["dates"]["recorded"]["ignition"], season.iso_utc(ig), f"{n} recorded ignition")
        same(f["dates"]["recorded"]["out"], season.iso_utc(out), f"{n} recorded out")
        assert f["dates"]["flags"], f"{n} is flagged and gives no reason"                # flagged
        assert set(f["dates"]["flags"]) <= set(s["dateFlags"]), f"{n}: a flag with no definition"
        same(f["dates"]["onTimeline"], placed is not None, f"{n} on the timeline")
        same(f["ignited"], placed, f"{n} timeline date")
        if placed is None:
            same((f["out"], f["dates"]["rule"]), (None, None), f"{n} is off the timeline")
        else:
            assert f["dates"]["rule"] in s["timelineRules"], f"{n}: placed by no stated rule"
        for raw in (n, str(ig), str(out)):                 # and the printed table shows them raw
            assert raw in table, f"the printed table does not show {raw} for {n}"
    info = s["impossibleDates"]
    same(info, {"fires": len(flagged),
                "onTimeline": sum(1 for f in flagged.values() if f["dates"]["onTimeline"]),
                "notOnTimeline": sum(1 for f in flagged.values() if not f["dates"]["onTimeline"]),
                "byFlag": {k: n for k in s["dateFlags"] for n in [sum(
                    1 for f in flagged.values() if k in f["dates"]["flags"])] if n},
                "byRule": {k: sum(1 for f in flagged.values() if f["dates"]["rule"] == k)
                           for k in s["timelineRules"]}}, "the count the page will state")
    same({k: v for k, v in summary["impossibleDates"].items() if k != "list"}, info,
         "the same count in the summary")
    same(summary["impossibleDates"]["list"],
         [{"fire": f["fire"], "flags": f["dates"]["flags"], "onTimeline": f["dates"]["onTimeline"],
           "rule": f["dates"]["rule"]} for f in s["fires"] if not f["dates"]["ok"]],
         "the summary's list of flagged fires")
    assert any(f"{len(flagged)} fires carry a date that cannot be true" in note
               for note in s["notes"]), "the file's notes do not state the count"
    same(len(s["fires"]), PINS["total"], "flagged fires are still in the total")       # counted
    same(sum(s["statusTally"].values()), PINS["total"], "and in the status tally")
    # The other direction: no fire that passed as possible carries a date that is not.
    seen = {}
    for d in load(f"{YEAR}.days.json")["days"]:
        doc = load(d["fires"]["file"])
        for feat in doc["data"]["features"]:
            seen.setdefault(feat["properties"]["FIRE_NUMBER"], []).append(
                season.parse_utc(doc["fetchedAt"]))
    for f in s["fires"]:
        if not f["dates"]["ok"]:
            continue
        ig, out = f["ignitionMs"], f["outMs"]
        assert ig is not None and local_day(ig)[:4] == str(YEAR), f"{f['fire']}: ignition year"
        assert ig <= cap_ms and (out is None or ig <= out <= cap_ms), f"{f['fire']}: order"
        assert (out is None) == (f["statusAtCapture"] != "Out"), f"{f['fire']}: out and status"
        assert all(ig <= t for t in seen.get(f["fire"], [])), f"{f['fire']}: listed too early"
        same((f["ignited"], f["out"]), (local_day(ig), local_day(out) if out else None),
             f"{f['fire']} local dates")
    # V30852: the capture says 2025, six dated records say 15 July 2026, the file keeps both
    v = flagged["V30852"]["dates"]
    same((v["rule"], v["statusDays"]["ignitionAsKnown"], v["recorded"]["ignitionLocalDate"]),
         ("dated-record", ["2026-07-15T23:04:06Z"], "2025-07-15"), "V30852 evidence")
    return f"{len(flagged)} flagged, {info['onTimeline']} placed by a rule, every one kept"


@test
def hindsight_cannot_reach_the_dispatch_model_by_accident():
    """The season file is not something the page's feed code can swallow, and its one size
    goes by a name that nothing in the page or the model reads."""
    s = load(f"{YEAR}.json")
    assert s["notes"][0].startswith("HINDSIGHT."), "the first note must say hindsight"
    assert "dispatch model" in s["notes"][0], "the first note must name the dispatch model"
    for f in s["fires"]:
        same(list(f), RECORD_KEYS, f"{f['fire']} keys")
    sizes = [k for k in RECORD_KEYS if "size" in k.lower() or k.lower().endswith("ha")]
    same(sizes, ["hindsightSizeHa"], "size-like keys in a fire record")
    assert "hindsight" in s["fields"]["hindsightSizeHa"].lower(), "the field's own definition"
    same(sorted(s["fields"]), sorted(RECORD_KEYS), "documented fields")

    def keys(o):
        if isinstance(o, dict):
            for k, v in o.items():
                yield k
                yield from keys(v)
        elif isinstance(o, list):
            for v in o:
                yield from keys(v)

    # The names a size travels under on its way to the model. If either file stops using its
    # name, this guard is guarding the wrong word and must be looked at again.
    assert "CURRENT_SIZE" in (ROOT / "app" / "feeds.js").read_text(), (
        "app/feeds.js no longer reads a size from CURRENT_SIZE: revisit this guard")
    assert "sizeHa" in (ROOT / "sim" / "assign.js").read_text(), (
        "sim/assign.js no longer reads sizeHa: revisit this guard")
    used = set(keys(s))
    for name in ("sizeHa", "CURRENT_SIZE", "FIRE_SIZE_HECTARES", "size", "features", "data",
                 "fetchedAt", "properties"):
        assert name not in used, f"the season file has a key named {name!r}"
    return "one size, named hindsightSizeHa; no key the page or the model reads a size from"


def live_feeds():
    """ARC and FEEDS out of pipeline/live.py, with the wind grid the wind feed's address is
    built from: those five assignments are evaluated on their own, with `str` as the only
    builtin. The fetcher is not imported and nothing else in it runs."""
    tree = ast.parse((ROOT / "pipeline" / "live.py").read_text())
    names = (["WIND_LATS"], ["WIND_LONS"], ["WIND_POINTS"], ["ARC"], ["FEEDS"])
    wanted = [node for node in tree.body if isinstance(node, ast.Assign)
              and [getattr(t, "id", None) for t in node.targets] in names]
    same(len(wanted), 5, "the ARC, FEEDS and wind-grid assignments in pipeline/live.py")
    # One dictionary for globals and locals: a comprehension's inner scope reads globals.
    scope = {"__builtins__": {"str": str}}
    exec(compile(ast.Module(wanted, []), "pipeline/live.py", "exec"), scope)
    return scope["FEEDS"]


@test
def status_days_are_in_the_live_mirrors_shape():
    """The property names, their order, the filter and the tolerance are read out of
    pipeline/live.py, so a status day cannot drift away from what the mirror serves."""
    feeds, wanted = live_feeds(), {}
    for name, key, source in (("fires", "FIRE_PROPS", season.FIRES_SOURCE),
                              ("perims", "PERIM_PROPS", season.PERIMS_SOURCE)):
        url = feeds[name]["url"]
        query = urllib.parse.parse_qs(urllib.parse.urlsplit(url).query)
        same(source, url.split("?")[0], f"the {name} source against pipeline/live.py")
        fields = query["outFields"][0].split(",")
        same(list(getattr(season, key)), fields, f"season.{key} against pipeline/live.py")
        same(query["where"], ["FIRE_STATUS <> 'Out'"], f"the {name} filter in pipeline/live.py")
        wanted[name] = (fields, source)
    same(float(urllib.parse.parse_qs(urllib.parse.urlsplit(feeds["perims"]["url"]).query)[
        "maxAllowableOffset"][0]), season.GENERALISE_DEG, "the generalisation tolerance")
    index = load(f"{YEAR}.days.json")
    same(index["shape"], {"document": ["fetchedAt", "source", "data"],
                          "feature": ["type", "geometry", "properties"],
                          "fires": wanted["fires"][0], "perims": wanted["perims"][0]},
         "the shape the index states")
    features = 0
    for d in index["days"]:
        for name in ("fires", "perims"):
            file = d[name]["file"]
            same(file, f"days/{d['date']}/{name}.json", "a day file's path")
            raw = (SEASON / file).read_bytes()
            doc = json.loads(raw)
            same(list(doc), ["fetchedAt", "source", "data"], f"{file} keys")
            same(doc["source"], wanted[name][1], f"{file} source")
            same(doc["data"]["type"], "FeatureCollection", f"{file} type")
            same(local_day(season.parse_utc(doc["fetchedAt"])), d["date"], f"{file} local date")
            same(raw, json.dumps(doc, separators=(",", ":")).encode(),
                 f"{file} is serialised the way pipeline/live.py writes")
            for f in doc["data"]["features"]:
                same(list(f), ["type", "geometry", "properties"], f"{file} feature")
                same(list(f["properties"]), wanted[name][0], f"{file} properties")
                assert f["properties"]["FIRE_STATUS"] not in (None, "Out"), f"{file}: an out fire"
                features += 1
            same((len(raw), hashlib.sha256(raw).hexdigest()), (d[name]["bytes"], d[name]["sha256"]),
                 f"{file} against its index entry")
            same(len(doc["data"]["features"]), d[name]["count"], f"{file} count")
        fires = load(d["fires"]["file"])
        same(d["fetchedAt"], fires["fetchedAt"], f"{d['date']} time")
        listed = [f["properties"]["FIRE_NUMBER"] for f in fires["data"]["features"]]
        same(len(set(listed)), len(listed), f"{d['date']}: a fire listed twice")
        for f in fires["data"]["features"]:
            same(f["geometry"]["type"], "Point", f"{d['date']} fire geometry")
        for p in load(d["perims"]["file"])["data"]["features"]:
            assert p["geometry"]["type"] in ("Polygon", "MultiPolygon"), "a perimeter's geometry"
            assert p["properties"]["FIRE_NUMBER"] in listed, (
                f"{d['date']}: a perimeter for {p['properties']['FIRE_NUMBER']}, which the "
                "day does not list")
    return f"{len(index['days'])} days, {features:,} features, all in the mirror's shape"


@test
def status_days_carry_only_what_was_known_that_day():
    s, index = load(f"{YEAR}.json"), load(f"{YEAR}.days.json")
    by_number = {f["fire"]: f for f in s["fires"]}
    kinds, renumbered = {}, []
    for d in index["days"]:
        kinds[d["kind"]] = kinds.get(d["kind"], 0) + 1
        fires = load(d["fires"]["file"])["data"]["features"]
        if d["kind"] == "mirror-history":       # the recovered copy itself, byte for byte
            for name in ("fires", "perims"):
                same((d[name]["bytes"], d[name]["sha256"]),
                     (d["source"][name]["bytes"], d["source"][name]["sha256"]),
                     f"{d['date']} {name} against the recovered copy")
        elif d["kind"] == "repository-snapshot":   # data/snapshot.json, minus two properties
            same(d["source"]["file"], "data/snapshot.json", "the snapshot day's source")
            snap = json.loads((ROOT / d["source"]["file"]).read_bytes())
            for name, key in (("fires", "fires"), ("perims", "perimeters")):
                got = load(d[name]["file"])["data"]["features"]
                same(len(got), len(snap[key]["features"]), f"{d['date']} {name} count")
                for a, b in zip(got, snap[key]["features"]):
                    same(a["geometry"], b["geometry"], f"{d['date']} geometry")
                    same(a["properties"], {k: b["properties"][k] for k in a["properties"]},
                         f"{d['date']} properties")
        elif d["kind"] == "capture" and d["source"]["manifest"] == s["capture"]["manifest"]:
            # the season's own capture: that copy's fires that were not out, and no others
            want = {f["fire"]: (f["statusAtCapture"], f["hindsightSizeHa"], f["ignitionMs"])
                    for f in s["fires"] if f["statusAtCapture"] not in (None, "Out")}
            got = {f["properties"]["FIRE_NUMBER"]: (
                f["properties"]["FIRE_STATUS"], f["properties"]["CURRENT_SIZE"],
                f["properties"]["IGNITION_DATE"]) for f in fires}
            same(got, want, f"{d['date']} against the capture it came from")
        else:
            same(d["kind"], "capture", f"{d['date']}: an unknown kind of day")
        # A number the season file does not have is named, with the season fire that has its
        # sequence number. Where there is one, it is the same fire: same point, same ignition.
        strangers = sorted(f["properties"]["FIRE_NUMBER"] for f in fires
                           if f["properties"]["FIRE_NUMBER"] not in by_number)
        same([x["fire"] for x in d["notInSeasonFile"]], strangers, f"{d['date']} strangers")
        for x in d["notInSeasonFile"]:
            if x["sameSequenceNumberAs"] is None:
                continue
            now = by_number[x["sameSequenceNumberAs"]]
            then = [f for f in fires if f["properties"]["FIRE_NUMBER"] == x["fire"]][0]
            lon, lat = then["geometry"]["coordinates"]
            same((round(lat, 4), round(lon, 4), then["properties"]["IGNITION_DATE"]),
                 (now["lat"], now["lon"], now["ignitionMs"]),
                 f"{x['fire']} on {d['date']} and {now['fire']} in the season file")
            renumbered.append(f"{x['fire']} is {now['fire']}")
    same(sorted(kinds), sorted(index["kinds"]), "every kind of day the index defines is in use")
    # What a day knew is not what hindsight says. Had the days been cut from the season file
    # these would agree, so the disagreement is the proof that they were not.
    first = load(index["days"][0]["fires"]["file"])["data"]["features"]
    differ = sum(1 for f in first if f["properties"]["FIRE_NUMBER"] in by_number
                 and f["properties"]["CURRENT_SIZE"]
                 != by_number[f["properties"]["FIRE_NUMBER"]]["hindsightSizeHa"])
    assert differ > 0, "the first status day's sizes all equal hindsight: that cannot be right"
    return (f"{kinds.get('mirror-history', 0)} recovered copies, "
            f"{kinds.get('repository-snapshot', 0)} snapshot, {kinds.get('capture', 0)} capture; "
            f"{differ} of {len(first)} sizes on {index['days'][0]['date']} differ from "
            f"hindsight; renumbered: {', '.join(renumbered) or 'none'}")


@test
def provenance_names_every_file_and_every_raw_input():
    prov, index = load(f"{YEAR}.prov.json"), load(f"{YEAR}.days.json")
    house = json.loads((ROOT / "data" / "snapshot.prov.json").read_bytes())
    same(list(prov)[:len(house)], list(house), "the keys of data/*.prov.json, in their order")
    same(list(prov)[len(house):], ["captureFolders", "inputs", "outputs", "documentation"], "what this sidecar adds")
    raw = (SEASON / f"{YEAR}.prov.json").read_bytes()
    same(raw, (json.dumps(prov, indent=2) + "\n").encode("ascii"), "the sidecar's formatting")
    same(prov["generator"], "pipeline/season.py", "generator")
    same((prov["licence"], prov["attribution"]), (house["licence"], house["attribution"]),
         "licence and attribution, as the other BC Wildfire Service sidecar words them")
    for phrase in ("The Information was modified", "does not endorse", "Not for emergency use",
                   "must never be an input to the dispatch model"):
        same(prov["notes"].count(phrase), 1, f"the notes say {phrase!r}")
    out = {o["file"]: o for o in prov["outputs"]}
    # The guard file and its sidecar are a ruling about the season, not season output:
    # they are pinned by their own digest test (tests/guard/check.py), so the provenance
    # must not claim to cover them and must not flag them as missing from its outputs.
    guard = {f"{YEAR}.guard.json", f"{YEAR}.guard.prov.json"}
    on_disk = sorted(p.relative_to(SEASON).as_posix() for p in SEASON.rglob("*")
                     if p.is_file() and p.name != f"{YEAR}.prov.json"
                     and p.name not in guard)
    same(sorted(out), on_disk, "files the provenance covers")
    for name, o in out.items():
        data = (SEASON / name).read_bytes()
        same((len(data), hashlib.sha256(data).hexdigest()), (o["bytes"], o["sha256"]), name)
    hashes = {i["sha256"] for i in prov["inputs"]}
    for i in prov["inputs"]:
        assert re.fullmatch(r"[0-9a-f]{64}", i["sha256"]) and i["bytes"] > 0 and i["what"], (
            f"an input is not named by sha256 and size: {i}")
    for d in index["days"]:
        src = d["source"]
        need = ([src["fires"]["sha256"], src["perims"]["sha256"]] if d["kind"] == "mirror-history"
                else [src["sha256"]] if d["kind"] == "repository-snapshot"
                else [src["manifest"]["sha256"]] + [f["sha256"] for f in src["files"]])
        assert set(need) <= hashes, f"{d['date']}: a raw input is missing from the provenance"
    snapshot = hashlib.sha256((ROOT / "data" / "snapshot.json").read_bytes()).hexdigest()
    assert snapshot in hashes, "data/snapshot.json is not the file the snapshot day was made from"
    assert index["mirrorHistory"]["index"]["sha256"] in hashes, "the mirror history's own index"
    return f"{len(out)} files covered, {len(prov['inputs'])} raw inputs named by sha256"


@test
def the_time_zone_database_agrees():
    """Every local date here depends on it. If this fails, the dates moved and the data did not."""
    for text, offset in (("2026-02-27T19:00:01Z", "-08:00"), ("2026-07-01T12:00:00Z", "-07:00"),
                         ("2026-10-02T02:01:28Z", "-07:00")):
        same(season.utc_offset(season.parse_utc(text)), offset, f"UTC offset at {text}")
    same(season.local_date(season.parse_utc("2026-08-10T06:59:59Z")), "2026-08-09", "23:59:59")
    same(season.local_date(season.parse_utc("2026-08-10T07:00:00Z")), "2026-08-10", "00:00:00")
    same(season.iso_utc(-17041510053000), "1429-12-23T07:12:27Z", "a date in 1429")
    same(season.local_date(-2208963600000), "1899-12-31", "a date before standard time")
    same(season.iso_utc(None), None, "no date")
    same(load(f"{YEAR}.json")["capture"]["utcOffset"], "-07:00", "the capture's offset")
    return "America/Vancouver: -08:00 in February, -07:00 in July and at the capture"


def sections(path, cut):
    """The parts of a document that are about the season files."""
    return [part for part in re.split(cut, (ROOT / path).read_text())
            if "data/season/" in part or part.startswith("## The season files")]


DOCUMENTS = (("data/README.md", r"\n(?=## )"), ("DATA-SOURCES.md", r"\n(?=## )"),
             ("NOTICE", r"\n\s*\n"))


@test
def nothing_personal_in_any_file_this_adds():
    """No home path, no machine name, no e-mail address. The machine's name is read at run
    time and the path patterns are built from pieces, so that this file holds neither."""
    added = [ROOT / "pipeline" / "season.py", HERE / "check.py"]
    added += sorted(p for p in SEASON.rglob("*") if p.is_file())
    texts = {p.relative_to(ROOT).as_posix(): p.read_bytes() for p in added}
    for path, cut in DOCUMENTS:
        parts = sections(path, cut)
        assert parts, f"{path} has no part about the season files"
        texts[path + " (the season part)"] = "\n".join(parts).encode()
    slash = b"/"
    roots = b"|".join(re.escape(slash + name + slash) for name in (b"home", b"Users", b"root"))
    patterns = {
        "a home path": re.compile(roots + rb"|[A-Za-z]:\\+Users"),
        "an e-mail address": re.compile(rb"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+\.[A-Za-z]{2,}")}
    host = socket.gethostname().split(".")[0]
    if len(host) >= 5 and host.lower() != "localhost":
        patterns["this machine's name"] = re.compile(
            rb"(?<![A-Za-z0-9])" + re.escape(host.encode()) + rb"(?![A-Za-z0-9])", re.I)
    hits = [f"{name}: {what} ({m.group(0)[:40]!r})" for name, data in texts.items()
            for what, pat in patterns.items() for m in [pat.search(data)] if m]
    assert not hits, "; ".join(hits)
    return f"{len(texts)} files and document sections, {len(patterns)} patterns, nothing found"


@test
def the_documents_say_what_the_data_says():
    """data/README.md quotes numbers. Each is rebuilt here from the files, so a regeneration
    that moves a number fails until the page that quotes it is corrected."""
    s, summary = load(f"{YEAR}.json"), load(f"{YEAR}.summary.json")
    index = load(f"{YEAR}.days.json")
    parts = sections(*DOCUMENTS[0])
    same(len(parts), 1, "sections of data/README.md about the season files")
    page = squeeze(parts[0])
    fires = s["fires"]
    flagged = [f for f in fires if not f["dates"]["ok"]]
    under, span = summary["under1ha"], summary["ignitionToOut"]
    peak, info = summary["timeline"]["peak"], summary["impossibleDates"]

    def by_size(counts):
        return ", ".join(f"{n:,} {k.lower()}" for k, n in sorted(
            counts.items(), key=lambda kv: -kv[1]))

    rows = [
        f"| Fires in the layer | {s['total']:,} |",
        f"| Status when the copy was taken | {by_size(s['statusTally'])} |",
        f"| Under one hectare when the copy was taken | {under['fires']:,}, of which "
        f"{under['out']:,} were out |",
        f"| Median time from ignition to out | {span['medianDays']} days, over the "
        f"{span['fires']:,} fires that are out and have possible dates |",
        f"| Most fires burning at the end of a day | {peak['active']}, on "
        f"{', '.join(peak['dates'])} |",
        f"| Suspected cause | {by_size(summary['byCause'])} |",
        "| Fire centre, by the letter that begins the fire number | "
        + ", ".join(f"{k} {n}" for k, n in sorted(summary["byCentre"].items())) + " |",
        f"| Fires with an impossible date | {info['fires']}, of which a rule places "
        f"{info['onTimeline']} on the timeline |"]
    rows += [f"| {d['date']} | {d['kind'].replace('-', ' ')} | {d['fetchedAt']} | "
             f"{d['fires']['count']} | {d['perims']['count']} |" for d in index["days"]]
    for f in flagged:
        d = f["dates"]
        rows.append(f"| {f['fire']} | {d['recorded']['ignition']} | "
                    f"{d['recorded']['out'] or 'none'} | "
                    + ", ".join(f"`{k}`" for k in d["flags"]) + " | "
                    + (f"{f['ignited']}, `{d['rule']}`" if d["onTimeline"] else "no") + " |")

    revised, cover, numbering = (summary["ignitionRevised"], summary["coverage"],
                                 summary["numbering"])
    then = summary["statusDays"]["days"][0]["hindsightAtThatMoment"]
    top = max(int(f["fire"][2:]) for f in fires)
    early = sum(1 for f in fires if f["ignited"] and f["ignited"] < fires[0]["ignited"])
    known = {f["fire"]: f["dates"]["statusDays"] for f in flagged if f["dates"]["statusDays"]}
    says = [
        f"{under['fires']:,} of these {s['total']:,} fires were under one hectare",
        f"of the {revised['firesCompared']} fires that are in both this file and a status day, "
        f"{revised['firesCompared'] - revised['sameInstant']} carry a different ignition time",
        f"{revised['earlierAtCapture']} of those earlier, and for "
        f"{revised['differentLocalDate']} the local date itself moved",
        f"{index['mirrorHistory']['fireCopies']} dated copies each",
        f"taken {s['capture']['capturedAt']}",
        f"out of the {len(summary['timeline']['days'])} dates",
        f"the status days list {cover['ofThemInSeasonFile']} of the season's {s['total']:,} "
        "fires",
        f"The other {cover['seasonFiresNeverListed']:,} fires of the season are on no status "
        "day",
        f"Each was out before the copy of {long_date(s['capture']['localDate'])} was taken",
        f"{then['burning']} fires were burning at the moment of the copy; the copy listed "
        f"{then['alsoListed']} of them and not the other {then['notListed']}",
        f"run to {top}, so {top - len(fires)} numbers below that are not in the layer",
        f"{word(info['fires']).capitalize()} of the {s['total']:,} fires carry a date that "
        "cannot be true",
        f"{word(len(info['byFlag'])).capitalize()} of those {word(len(s['dateFlags']))} tests "
        "find something",
        f"{numbering['ignitedWithinOneDay']:,} of {numbering['pairs']:,} ignited within a day "
        f"of the fire numbered before them, and the widest gap is "
        f"{numbering['largestGapDays']} days",
        f"{word(len(known['V30852']['listedOn'])).capitalize()} status days, 8 to 13 August, "
        f"give its ignition as {known['V30852']['ignitionAsKnown'][0]}",
        f"the {word(len(known['G90400']['listedOn']))} status days that list it",
        f"{word(early).capitalize()} fires have an ignition date earlier than that",
        f"The lowest-numbered fire ignited on {long_date(fires[0]['ignited'])}",
        f"The timeline begins on {long_date(summary['timeline']['from'])}",
        "hindsightSizeHa", "America/Vancouver", "### No lookahead", "### What a status day is",
        "### Impossible dates", "is never repaired and never dropped",
        "any fire would have burned differently"]
    for d in index["days"]:                  # a fire the season file has under another number
        for x in d["notInSeasonFile"]:
            says.append(f"They also list {x['fire']}, on {long_date(d['date'])}, which is the "
                        f"season file's {x['sameSequenceNumberAs']}")
    on_a_day = {p["properties"]["FIRE_NUMBER"] for d in index["days"]
                for p in load(d["fires"]["file"])["data"]["features"]}
    assert all(f["statusAtCapture"] == "Out" for f in fires if f["fire"] not in on_a_day), (
        "data/README.md says every fire on no status day was out at capture; one was not")
    missing = [x for x in rows + says if squeeze(x) not in page]
    assert not missing, "data/README.md does not say: " + " // ".join(missing)

    # Every flagged fire is argued, by name. Where the argument leans on the fires numbered
    # either side, the dates it gives for them must be the ones in dates.bracket.
    argued = 0
    for f in flagged:
        d = f["dates"]
        bullet = re.search(r"\*\*" + f["fire"] + r"\*\*.*?(?=\n- |\n\n)", parts[0], re.S)
        assert bullet, f"data/README.md has no paragraph arguing {f['fire']}"
        if not re.search(r"number(ed| sits)", bullet.group(0)):
            continue
        near = sorted({v["ignited"] for v in d["bracket"].values() if v})
        same(len({day[:7] for day in near}), 1, f"{f['fire']}: its neighbours' months")
        quote = (" and ".join(str(int(day[8:])) for day in near)
                 + " " + MONTHS[int(near[0][5:7])])
        assert quote in squeeze(bullet.group(0)), (
            f"data/README.md on {f['fire']}: the fires numbered either side ignited on "
            f"{quote}, and the page does not say so")
        argued += 1

    terms = ["Contains information licensed under the Open Government Licence – British "
             "Columbia.", "2.0", "BC Wildfire Service", "The Information was modified",
             "does not endorse", "Not for emergency use"]
    for path, cut in DOCUMENTS[1:]:
        found = [squeeze(p) for p in sections(path, cut)]
        assert any(all(t in p for t in terms) for p in found), (
            f"{path}: no part about data/season/ carries all of the licence and its version, "
            "the attribution, the modification notice, the non-endorsement notice and the "
            "emergency notice")
    for t in terms[:1] + terms[2:]:
        assert t in page, f"data/README.md: the season section does not say {t!r}"
    last = sections(*DOCUMENTS[1])[-1].rstrip()
    assert (ROOT / "DATA-SOURCES.md").read_text().rstrip().endswith(last), (
        "the season section is not the last section of DATA-SOURCES.md")
    return (f"data/README.md: {len(rows)} table rows, {len(says)} statements and {argued} "
            "neighbour dates match the data; NOTICE and DATA-SOURCES.md carry the terms")


# ============================================================================================
# 2. A SYNTHETIC SEASON, small enough to check by hand
# ============================================================================================
INC_URL = season.FIRES_SOURCE[:-len("/query")]
PER_URL = season.PERIMS_SOURCE[:-len("/query")]
SYN = 2019


def ms(text):
    return season.parse_utc(text)


def incident(number, ignition, out, status, size, centre):
    return {"type": "Feature", "id": 0,
            "geometry": {"type": "Point", "coordinates": [-120.123456789, 50.987654321]},
            "properties": {
                "FIRE_YEAR": SYN, "IGNITION_DATE": ignition and ms(ignition), "FIRE_STATUS": status,
                "FIRE_CENTRE": centre, "ZONE": 1, "FIRE_ID": int(number[2:]), "LATITUDE": 50.9877,
                "LONGITUDE": -120.1235, "CURRENT_SIZE": size, "FEATURE_CODE": "X", "OBJECTID": 0,
                "GlobalID": number, "RESPONSE_TYPE_DESC": None,
                "FIRE_OUT_DATE": out and ms(out), "INCIDENT_NAME": number, "FIRE_NUMBER": number,
                "FIRE_CAUSE": "Lightning", "FIRE_TYPE": "Fire",
                "GEOGRAPHIC_DESCRIPTION": "Somewhere ", "FIRE_URL": "https://example.invalid/",
                "FIRE_OF_NOTE_IND": "N", "WAS_FIRE_OF_NOTE_IND": "N"}}


def perimeter(number, status, ring):
    return {"type": "Feature", "id": 0, "geometry": {"type": "Polygon", "coordinates": [ring]},
            "properties": {"FIRE_NUMBER": number, "VERSION_NUMBER": 1, "FIRE_YEAR": SYN,
                           "FIRE_SIZE_HECTARES": 10.5, "SOURCE": "x", "LOAD_DATE": 0,
                           "TRACK_DATE": ms("2019-07-06T00:00:00Z"), "FIRE_STATUS": status,
                           "FEATURE_CODE": "X", "OBJECTID": 0, "GlobalID": number,
                           "FIRE_URL": "https://example.invalid/"}}


def write_capture(folder, captured, incidents, perimeters, complete=True, said=None):
    """A capture folder as the generator expects one: pages, layer descriptions, a manifest."""
    folder.mkdir(parents=True)
    layer = json.dumps({"dateFieldsTimeReference": {"timeZone": "UTC"},
                        "editingInfo": {"dataLastEditDate": ms(captured) - 60000}}).encode()
    half = len(incidents) // 2      # two pages, so that paging is exercised
    files = {
        "incidents.layer.json": layer, "perimeters.layer.json": layer,
        "incidents.page-000.geojson": json.dumps({"features": incidents[:half]}).encode(),
        "incidents.page-001.geojson": json.dumps({"features": incidents[half:]}).encode(),
        "perimeters.page-000.geojson": json.dumps({"features": perimeters}).encode()}
    for name, data in files.items():
        (folder / name).write_bytes(data)

    def by_status(features):
        return count(f["properties"]["FIRE_STATUS"] for f in features)

    manifest = {
        "capturedAt": captured, "localDate": said or season.local_date(ms(captured)),
        "layers": {
            "incidents": {"url": INC_URL, "where": "1=1", "countOnly": len(incidents),
                          "byStatus": by_status(incidents), "complete": complete},
            "perimeters": {"url": PER_URL, "where": "1=1", "countOnly": len(perimeters),
                           "byStatus": by_status(perimeters), "complete": True}},
        "requests": [{"file": name, "url": "https://example.invalid/" + name, "bytes": len(data),
                      "sha256": hashlib.sha256(data).hexdigest()} for name, data in files.items()]}
    (folder / "MANIFEST.json").write_text(json.dumps(manifest))


def mirror_fire(number, status, size, ignition):
    props = {"FIRE_NUMBER": number, "FIRE_STATUS": status, "FIRE_CAUSE": "Lightning",
             "INCIDENT_NAME": number, "GEOGRAPHIC_DESCRIPTION": "Somewhere ", "CURRENT_SIZE": size,
             "IGNITION_DATE": ms(ignition), "FIRE_URL": "https://example.invalid/",
             "FIRE_OF_NOTE_IND": "N", "RESPONSE_TYPE_DESC": "Full"}
    return {"type": "Feature", "geometry": {"type": "Point", "coordinates": [-120.1, 50.9]},
            "properties": props}


def mirror_perim(number, status):
    return {"type": "Feature",
            "geometry": {"type": "Polygon",
                         "coordinates": [[[-120, 50], [-120, 50.1], [-119.9, 50], [-120, 50]]]},
            "properties": {"FIRE_NUMBER": number, "FIRE_STATUS": status,
                           "FIRE_SIZE_HECTARES": 3.5, "TRACK_DATE": ms("2019-07-06T00:00:00Z")}}


def write_mirror(folder, copies):
    """copies: (name, fetchedAt, features), each written the way pipeline/live.py writes."""
    folder.mkdir(parents=True)
    index = []
    for name, fetched, features in copies:
        sub = fetched.replace("-", "").replace(":", "")
        source = {"fires": season.FIRES_SOURCE, "perims": season.PERIMS_SOURCE}.get(name, "heat")
        data = json.dumps({"fetchedAt": fetched, "source": source,
                           "data": {"type": "FeatureCollection", "crs": season.CRS,
                                    "features": features}}, separators=(",", ":")).encode()
        (folder / sub).mkdir(exist_ok=True)
        (folder / sub / f"{name}.json").write_bytes(data)
        index.append({"name": name, "fetchedAt": fetched, "folder": sub, "file": f"{name}.json",
                      "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()})
    (folder / "INDEX.json").write_text(json.dumps({"source": "synthetic", "copies": index}))


RING = [[-120.0, 50.0], [-120.0, 50.05], [-120.0, 50.1], [-119.95, 50.10004], [-119.9, 50.1],
        [-119.9, 50.0], [-119.95000001, 50.00003], [-120.0, 50.0]]


def synthetic_world(root):
    """Sixteen fires. The comment on each says what must happen to it.

    The capture is taken 2019-07-11T02:00Z, which is 19:00 on 10 July in Vancouver."""
    fires = [
        # possible dates: ignited on the 1st, out on the 3rd
        incident("K10001", "2019-07-01T20:00:00Z", "2019-07-03T20:00:00Z", "Out", 0.5, 5),
        # one second before local midnight: ignited on the 4th, not the 5th. Not out.
        incident("K10002", "2019-07-05T06:59:59Z", None, "Under Control", 12, 5),
        # local midnight exactly: ignited on the 5th. Out at local midnight on the 9th.
        incident("K10003", "2019-07-05T07:00:00Z", "2019-07-09T07:00:00Z", "Out", 0, 5),
        # ignition a year early, on no status day: flagged, not placed
        incident("C20004", "2018-07-02T20:00:00Z", "2019-07-04T20:00:00Z", "Out", 2, 7),
        # ignition a year early; two status days agree on 6 July 2019: placed by dated-record
        incident("C20005", "2018-07-06T20:00:00Z", "2019-07-09T20:00:00Z", "Out", 40, 7),
        # ignition a year early; the status days disagree on the date: not placed
        incident("C20006", "2018-07-06T20:00:00Z", "2019-07-09T20:00:00Z", "Out", 3, 7),
        # ignition a year early; a status day has a date, but one after the out date: not placed
        incident("C20007", "2018-07-06T20:00:00Z", "2019-07-06T10:00:00Z", "Out", 3, 7),
        # out thirty minutes before ignition, one local date: placed by same-local-day
        incident("V10008", "2019-07-08T20:00:00Z", "2019-07-08T19:30:00Z", "Out", 0.1, 2),
        # out a week before ignition: flagged, not placed
        incident("V10009", "2019-07-09T20:00:00Z", "2019-07-02T20:00:00Z", "Out", 0.2, 2),
        # ignites after the capture, so the capture's own day lists it before it ignites
        incident("N10010", "2019-07-20T20:00:00Z", None, "Being Held", 5, 6),
        # listed on a status day two days before its own ignition
        incident("N10011", "2019-07-08T20:00:00Z", None, "Being Held", 6, 6),
        # Out, and no out date
        incident("R10012", "2019-07-02T20:00:00Z", None, "Out", 0.3, 3),
        # an out date on a fire that is not out
        incident("R10013", "2019-07-02T20:00:00Z", "2019-07-04T20:00:00Z", "Under Control", 7, 3),
        # no ignition date at all
        incident("G10014", None, None, "Out of Control", 8, 4),
        # out after the capture was taken
        incident("G10015", "2019-07-02T20:00:00Z", "2019-07-15T20:00:00Z", "Out", 9, 4),
        # no status: possible dates, kept, counted as 'null', dropped by the mirror's filter
        incident("G10016", "2019-07-03T20:00:00Z", None, None, 0.9, 4),
    ]
    perims = [perimeter("K10002", "Under Control", RING), perimeter("K10001", "Out", RING),
              perimeter("G10016", None, RING)]
    series = root / "captures" / "series"
    write_capture(series / "2019-07-10", "2019-07-11T02:00:00Z", fires, perims)
    later = [f for f in fires if f["properties"]["FIRE_NUMBER"] in ("K10002", "N10011")]
    write_capture(series / "2019-07-11", "2019-07-12T02:00:00Z", later, perims[:1])
    write_capture(series / "2019-07-12", "2019-07-13T02:00:00Z", later, perims[:1], complete=False)
    early, noon = "2019-07-05T07:00:00Z", "2019-07-06T20:00:00Z"
    write_mirror(root / "captures" / "mirror-history", [
        # 13:00 on the 6th, local: superseded by the 23:30 copy below
        ("fires", "2019-07-06T20:00:00Z", [mirror_fire("K10003", "Out of Control", 1, early)]),
        ("perims", "2019-07-06T20:00:01Z", []),
        # 23:30 on the 6th, local, which is already the 7th in UTC: the LAST copy of the 6th
        ("fires", "2019-07-07T06:30:00Z", [
            mirror_fire("K20002", "Out of Control", 3, "2019-07-05T06:59:59Z"),   # later K10002
            mirror_fire("K10003", "Being Held", 2, early),
            mirror_fire("C20005", "Out of Control", 20, noon),
            mirror_fire("C20006", "Out of Control", 1, "2019-07-05T20:00:00Z"),
            mirror_fire("N10011", "Out of Control", 1, "2019-07-08T20:00:00Z")]),
        ("perims", "2019-07-07T06:30:01Z", [mirror_perim("K20002", "Out of Control")]),
        # 13:00 on the 7th, local: superseded by the snapshot, taken at 15:00 that day
        ("fires", "2019-07-07T20:00:00Z", [mirror_fire("K10003", "Being Held", 2, early)]),
        ("perims", "2019-07-07T20:00:01Z", []),
        ("heat", "2019-07-07T20:00:02Z", []),
    ])
    snapshot = {
        "retrievedAt": "2019-07-07T22:00:00+00:00", "note": "synthetic",
        "fires": {"type": "FeatureCollection", "features": [
            mirror_fire("K10002", "Under Control", 7, "2019-07-05T06:59:59Z"),
            mirror_fire("K10003", "Under Control", 2, early),
            mirror_fire("C20005", "Being Held", 30, noon),
            mirror_fire("C20006", "Being Held", 2, noon),
            mirror_fire("C20007", "Being Held", 3, noon)]},
        "perimeters": {"type": "FeatureCollection", "features": [
            mirror_perim("K10002", "Under Control")]}}
    for f in snapshot["fires"]["features"]:
        f["properties"]["FIRE_CENTRE"] = 5          # the snapshot's extra property
    for f in snapshot["perimeters"]["features"]:
        f["properties"]["FIRE_URL"] = "https://example.invalid/"
    (root / "snapshot.json").write_text(json.dumps(snapshot))
    return series / "2019-07-10", root / "snapshot.json"


def scratch():
    return tempfile.TemporaryDirectory(prefix="season-",
                                       dir=os.environ.get("AIRSHIPS_TMPDIR") or None)


@test
def synthetic_every_flag_and_both_rules():
    with scratch() as tmp:
        capture, snapshot = synthetic_world(pathlib.Path(tmp))
        files = season.build(season.read_raw(capture, None, snapshot))
        same(files, season.build(season.read_raw(capture, None, snapshot)), "two runs, same bytes")
        s = json.loads(files[f"{SYN}.json"])
        summary = json.loads(files[f"{SYN}.summary.json"])
    f = {x["fire"]: x for x in s["fires"]}
    same([x["fire"] for x in s["fires"]], sorted(f, key=lambda n: int(n[2:])), "sequence order")
    year, late = "ignition-outside-fire-year", "listed-before-ignition"
    want = {   # fire: (flags, rule, ignited, out)
        "K10001": ([], None, "2019-07-01", "2019-07-03"),
        "K10002": ([], None, "2019-07-04", None),
        "K10003": ([], None, "2019-07-05", "2019-07-09"),
        "C20004": ([year], None, None, None),
        "C20005": ([year], "dated-record", "2019-07-06", "2019-07-09"),
        "C20006": ([year], None, None, None),
        "C20007": ([year], None, None, None),
        "V10008": (["out-before-ignition"], "same-local-day", "2019-07-08", "2019-07-08"),
        "V10009": (["out-before-ignition"], None, None, None),
        "N10010": (["ignition-after-capture", late], None, None, None),
        "N10011": ([late], None, None, None),
        "R10012": (["out-missing"], None, None, None),
        "R10013": (["out-date-but-not-out"], None, None, None),
        "G10014": (["ignition-missing"], None, None, None),
        "G10015": (["out-after-capture"], None, None, None),
        "G10016": ([], None, "2019-07-03", None),
    }
    same(sorted(f), sorted(want), "every fire is kept")
    for n, (flags, rule, ignited, out) in want.items():
        d = f[n]["dates"]
        same(d.get("flags", []), flags, f"{n} flags")
        same(d["ok"], not flags, f"{n} ok")
        same((d.get("rule"), f[n]["ignited"], f[n]["out"]), (rule, ignited, out), f"{n} placement")
    same(sorted({k for x in s["fires"] for k in x["dates"].get("flags", [])}),
         sorted(season.DATE_FLAGS), "every flag the generator defines is exercised")
    same(sorted({x["dates"]["rule"] for x in s["fires"] if x["dates"].get("rule")}),
         sorted(season.TIMELINE_RULES), "every rule the generator defines is exercised")
    # never repaired: the published values are still there, on the placed fire too
    same(f["C20005"]["ignitionMs"], ms("2018-07-06T20:00:00Z"), "C20005 keeps the published value")
    same(f["C20005"]["dates"]["recorded"]["ignitionLocalDate"], "2018-07-06", "C20005 recorded")
    same(f["C20005"]["dates"]["statusDays"],
         {"listedOn": ["2019-07-06", "2019-07-07"], "ignitionAsKnown": ["2019-07-06T20:00:00Z"]},
         "C20005 evidence")
    same(f["C20006"]["dates"]["statusDays"]["ignitionAsKnown"],
         ["2019-07-05T20:00:00Z", "2019-07-06T20:00:00Z"], "C20006: the status days disagree")
    same(f["C20004"]["dates"]["statusDays"], None, "C20004 is on no status day")
    same(f["G10014"]["dates"]["recorded"], {"ignition": None, "ignitionLocalDate": None,
                                            "out": None, "outLocalDate": None}, "G10014 recorded")
    same(f["C20004"]["dates"]["bracket"], {"before": {"fire": "K10003", "ignited": "2019-07-05"},
                                           "after": {"fire": "G10016", "ignited": "2019-07-03"}},
         "C20004 is bracketed by the nearest fires with possible dates")
    same((f["K10001"]["name"], f["K10001"]["place"], f["K10001"]["lat"], f["K10001"]["lon"],
          f["K10001"]["centre"], f["K10001"]["hindsightSizeHa"], f["K10001"]["fireOfNote"]),
         ("K10001", "Somewhere ", 50.9877, -120.1235, "Kamloops", 0.5, False),
         "values pass through untouched, the trailing space too")
    same(s["total"], 16, "all sixteen are counted")
    same(s["statusTally"], {"Being Held": 2, "Out": 10, "Out of Control": 1, "Under Control": 2,
                            "null": 1}, "the tally includes the flagged fires and the null status")
    same(s["impossibleDates"], {
        "fires": 12, "onTimeline": 2, "notOnTimeline": 10,
        "byFlag": {"ignition-missing": 1, year: 4, "ignition-after-capture": 1, "out-missing": 1,
                   "out-date-but-not-out": 1, "out-after-capture": 1, "out-before-ignition": 2,
                   late: 2},
        "byRule": {"dated-record": 1, "same-local-day": 1}}, "the count the page will state")
    assert "C20005" in season.table(s) and "by rule dated-record" in season.table(s), "the table"
    # The timeline, by hand. On it: K10001 (1st to 3rd), G10016 (3rd, not out), K10002 (4th,
    # not out), K10003 (5th to 9th), C20005 (6th to 9th), V10008 (the 8th, and out the 8th).
    t = summary["timeline"]
    same([(x["date"][-2:], x["started"], x["out"], x["active"]) for x in t["days"]],
         [("01", 1, 0, 1), ("02", 0, 0, 1), ("03", 1, 1, 1), ("04", 1, 0, 2), ("05", 1, 0, 3),
          ("06", 1, 0, 4), ("07", 0, 0, 4), ("08", 1, 1, 4), ("09", 0, 2, 2), ("10", 0, 0, 2)],
         "timeline")
    same(t["peak"], {"active": 4, "dates": ["2019-07-06", "2019-07-07", "2019-07-08"]},
         "a tied peak names every day")
    same((t["firesOnTimeline"], t["firesNotOnTimeline"]), (6, 10), "timeline split")
    same(summary["ignitionToOut"], {"medianDays": 3.0, "medianHours": 72.0, "fires": 2,
                                    "outFiresLeftOut": 8}, "the median is of K10001 and K10003")
    same(summary["under1ha"], {"fires": 6, "out": 5, "notOut": 1, "sizeZero": 1, "sizeUnknown": 0},
         "under 1 ha")
    same(summary["numbering"], {"firesWithPossibleDates": 4, "pairs": 3, "ignitedTheSameDay": 0,
                                "ignitedWithinOneDay": 1, "ignitedWithinSevenDays": 3,
                                "largestGapDays": 3}, "numbering")
    return "16 invented fires: 8 flags, 2 rules, a tied peak, a median of two"


@test
def synthetic_status_days_last_copy_filter_and_shape():
    with scratch() as tmp:
        capture, snapshot = synthetic_world(pathlib.Path(tmp))
        files = season.build(season.read_raw(capture, None, snapshot))
        index = json.loads(files[f"{SYN}.days.json"])
        summary = json.loads(files[f"{SYN}.summary.json"])
        mirror = pathlib.Path(tmp) / "captures" / "mirror-history"
        last = (mirror / "20190707T063000Z" / "fires.json").read_bytes()
    same(index["dates"], ["2019-07-06", "2019-07-07", "2019-07-10"], "status days")
    d6, d7, d10 = index["days"]
    # the 6th: a copy fetched after UTC midnight is still the 6th in Vancouver, and is the last
    same((d6["kind"], d6["fetchedAt"], d6["source"]["copiesThatDay"]),
         ("mirror-history", "2019-07-07T06:30:00Z", 2), "6 July")
    same(files["days/2019-07-06/fires.json"], last, "a mirror day is the copy, byte for byte")
    same(d6["notInSeasonFile"], [{"fire": "K20002", "sameSequenceNumberAs": "K10002"}],
         "a renumbered fire is named, with the fire that has its sequence number now")
    same(d6["impossibleAsKnown"], [{"fire": "N10011", "flags": ["listed-before-ignition"],
                                    "ignition": "2019-07-08T20:00:00Z"}], "impossible as known")
    same(index["mirrorHistory"]["fireCopies"], 3, "the heat copy is not counted")
    # the 7th: the snapshot (15:00) is later than the mirror copy (13:00), and says what it
    # replaced
    same((d7["kind"], d7["fetchedAt"]), ("repository-snapshot", "2019-07-07T22:00:00Z"), "7 July")
    same(d7["source"]["supersedes"], [{"kind": "mirror-history", "at": "2019-07-07T20:00:00Z"}],
         "the superseded copy is named")
    snap = json.loads(files["days/2019-07-07/fires.json"])
    same(list(snap["data"]["features"][0]["properties"]), list(season.FIRE_PROPS),
         "the snapshot's extra property is dropped")
    # the 10th: the capture, filtered the way the mirror filters
    same(d10["kind"], "capture", "10 July")
    day = json.loads(files["days/2019-07-10/fires.json"])
    same(sorted(f["properties"]["FIRE_NUMBER"] for f in day["data"]["features"]),
         ["G10014", "K10002", "N10010", "N10011", "R10013"], "not Out, and not null")
    same(list(day["data"]["features"][0]), ["type", "geometry", "properties"], "no id")
    same(day["data"]["features"][0]["geometry"]["coordinates"], [-120.123456789, 50.987654321],
         "a fire's point is not rounded")
    same((day["fetchedAt"], day["source"]), ("2019-07-11T02:00:00Z", season.FIRES_SOURCE),
         "the capture day's time and source")
    perims = json.loads(files["days/2019-07-10/perims.json"])["data"]["features"]
    same([p["properties"]["FIRE_NUMBER"] for p in perims], ["K10002"], "perimeter filter")
    same(list(perims[0]["properties"]), list(season.PERIM_PROPS), "perimeter properties")
    same(perims[0]["geometry"]["coordinates"],
         [[[-120.0, 50.0], [-120.0, 50.1], [-119.9, 50.1], [-119.9, 50.0], [-120.0, 50.0]]],
         "collinear and near-collinear vertices go; four decimal places")
    # what a day knew is not what hindsight says: K10002 was 7 ha on the 7th and is 12 now
    k = [f for f in snap["data"]["features"] if f["properties"]["FIRE_NUMBER"] == "K10002"][0]
    same(k["properties"]["CURRENT_SIZE"], 7, "size as known on the 7th")
    s7 = summary["statusDays"]["days"][1]
    same((s7["fires"], s7["byStatus"], s7["under1ha"], s7["perimeters"]),
         (5, {"Being Held": 3, "Under Control": 2}, 0, 1), "summary of the 7th")
    same(s7["hindsightAtThatMoment"], {"burning": 3, "alsoListed": 2, "notListed": 1,
                                       "listedNotBurning": 3}, "hindsight at that moment")
    same(summary["coverage"], {"firesListedOnAStatusDay": 10, "ofThemInSeasonFile": 9,
                               "ofThemNotInSeasonFile": ["K20002"], "seasonFiresNeverListed": 7},
         "coverage")
    return "last copy across UTC midnight, a superseded copy named, filter, shape, renumbering"


def quietly(args):
    """season.main() without its printed table."""
    keep = sys.stdout, sys.stderr
    with open(os.devnull, "w") as nowhere:
        sys.stdout = sys.stderr = nowhere
        try:
            return season.main([str(a) for a in args])
        finally:
            sys.stdout, sys.stderr = keep


def tree(folder):
    return {p.relative_to(folder).as_posix(): p.read_bytes()
            for p in folder.rglob("*") if p.is_file()}


@test
def synthetic_adding_a_day_is_one_command():
    with scratch() as tmp:
        tmp = pathlib.Path(tmp)
        capture, snapshot = synthetic_world(tmp)
        out = tmp / "out"
        args = [capture, "--snapshot", snapshot, "--out", out]
        gate = ["--check", "--snapshot", snapshot, "--out", out]
        same(quietly(args), 0, "the command")
        before = tree(out)
        same(quietly(args + ["--check"]), 0, "--check against the raw inputs")
        same(quietly(gate), 0, "--check from the written files alone")
        same(quietly(args), 0, "the command again")
        same(tree(out), before, "a second run changes nothing")
        same(quietly(args + ["--through", "2019-07-11"]), 0, "one command adds a day")
        after = tree(out)
        same(sorted(set(after) - set(before)),
             ["days/2019-07-11/fires.json", "days/2019-07-11/perims.json"], "new files")
        a, b = json.loads(before[f"{SYN}.json"]), json.loads(after[f"{SYN}.json"])
        same((b["total"], b["statusTally"], b["capture"], fingerprint(b["fires"])),
             (a["total"], a["statusTally"], a["capture"], fingerprint(a["fires"])),
             "the season record stays pinned to its own capture")
        index = json.loads(after[f"{SYN}.days.json"])
        same(index["dates"], ["2019-07-06", "2019-07-07", "2019-07-10", "2019-07-11"],
             "status days")
        same([f["properties"]["FIRE_NUMBER"] for f in json.loads(
            after["days/2019-07-11/fires.json"])["data"]["features"]], ["K10002", "N10011"],
            "the added day lists what its own capture listed")
        prov = json.loads(after[f"{SYN}.prov.json"])
        added = index["days"][-1]["source"]
        assert added["manifest"]["sha256"] in {i["sha256"] for i in prov["inputs"]}, (
            "the added capture's manifest is not in the provenance")
        assert day_fingerprint(index, out) != day_fingerprint(
            json.loads(before[f"{SYN}.days.json"]), out), "the day fingerprint did not move"
        same(quietly(gate), 0, "and the gate holds")
        same(quietly(args + ["--check"]), 0, "--check uses the recorded range and folders")
        # A sibling later than --through is not read at all: the incomplete capture of the
        # 12th stopped nothing above, and stops the run the moment it is asked for.
        raises(lambda: season.read_raw(capture, None, snapshot, "2019-07-12"),
               "not marked complete")
        raises(lambda: season.read_raw(capture, None, snapshot, "2019-07-01"),
               "before the season")
        same(quietly(["--check", "--out", tmp / "nothing"]), 2, "no season files: exit 2")
    return "--through adds 2019-07-11 and the record stays pinned; a later capture is not read"


@test
def synthetic_the_gate_notices():
    """Mutations. Each is something a hand or a bad merge could do to the committed files."""
    with scratch() as tmp:
        tmp = pathlib.Path(tmp)
        capture, snapshot = synthetic_world(tmp)
        out = tmp / "out"
        season.write(season.build(season.read_raw(capture, None, snapshot)), SYN, out)

        def gate():
            try:
                return season.drift(season.build(season.read_committed(SYN, out, snapshot)),
                                    SYN, out)
            except season.SeasonError as e:
                return [str(e)]

        same(gate(), [], "untouched")
        caught = []

        def mutate(name, old, new, expect):
            path = out / name
            original = path.read_bytes()
            assert original.count(old) >= 1, f"mutation target {old!r} is not in {name}"
            path.write_bytes(original.replace(old, new, 1))
            problems = gate()
            path.write_bytes(original)
            assert any(expect in p for p in problems), f"{name} {old!r}: not noticed ({problems})"
            caught.append(name)

        # a published value changed by hand: what is derived from it no longer follows
        mutate(f"{SYN}.json", b'"hindsightSizeHa":0.5', b'"hindsightSizeHa":5.5', "summary.json")
        mutate(f"{SYN}.json", b'"ignitionMs":1562011200000', b'"ignitionMs":1562097600000',
               f"{SYN}.json")
        # a published value that nothing is derived from: the provenance's sha256 notices
        mutate(f"{SYN}.json", b'"name":"K10001"', b'"name":"K1000X"', "prov.json")
        # a derived value changed by hand
        mutate(f"{SYN}.json", b'"ignited":"2019-07-01"', b'"ignited":"2019-07-02"', f"{SYN}.json")
        mutate(f"{SYN}.json", b'"onTimeline":false', b'"onTimeline":true', f"{SYN}.json")
        mutate(f"{SYN}.json", b'"total":16', b'"total":17', f"{SYN}.json")
        mutate(f"{SYN}.summary.json", b'"medianDays":3.0', b'"medianDays":2.0', "summary.json")
        mutate(f"{SYN}.days.json", b'"count":5', b'"count":6', "days.json")
        mutate(f"{SYN}.prov.json", b'"generator": "pipeline/season.py"', b'"generator": null',
               "prov.json")
        # a status day changed by hand, one of each kind
        mutate("days/2019-07-06/fires.json", b'"CURRENT_SIZE":20', b'"CURRENT_SIZE":21',
               "not the recovered copy")
        mutate("days/2019-07-07/fires.json", b'"CURRENT_SIZE":7', b'"CURRENT_SIZE":8', "fires.json")
        mutate("days/2019-07-10/fires.json", b'"CURRENT_SIZE":12', b'"CURRENT_SIZE":13',
               "disagree on K10002")
        mutate("days/2019-07-10/fires.json", b'"FIRE_STATUS":"Being Held"', b'"FIRE_STATUS":"Out"',
               "the mirror drops those")
        (out / "days" / "2019-07-08").mkdir()
        (out / "days" / "2019-07-08" / "fires.json").write_bytes(b"{}")
        assert any("not produced by the generator" in p for p in gate()), "a stray file"
        shutil.rmtree(out / "days" / "2019-07-08")
        (out / "days" / "2019-07-06" / "perims.json").rename(out / "kept")
        assert any("cannot read" in p for p in gate()), "a missing day file"
        (out / "kept").rename(out / "days" / "2019-07-06" / "perims.json")
        same(gate(), [], "restored")
        snapshot.write_bytes(snapshot.read_bytes().replace(b'"note": "synthetic"',
                                                           b'"note": "edited"'))
        assert any("was made from" in p for p in gate()), "a snapshot that has been replaced"
    return f"{len(caught) + 3} mutations of the written files, every one noticed"


@test
def synthetic_inputs_that_are_not_what_they_say_stop_the_run():
    refused = []
    with scratch() as tmp:
        tmp = pathlib.Path(tmp)
        capture, snapshot = synthetic_world(tmp)
        mirror = tmp / "captures" / "mirror-history"

        def refuse(fn, fragment):
            refused.append(raises(fn, fragment))

        page = capture / "incidents.page-000.geojson"
        original = page.read_bytes()
        assert b'"CURRENT_SIZE": 0.5' in original, "the byte this test changes is not there"
        page.write_bytes(original.replace(b'"CURRENT_SIZE": 0.5', b'"CURRENT_SIZE": 0.6'))
        refuse(lambda: season.read_raw(capture, None, snapshot), "not the file its manifest")
        page.write_bytes(original)

        def odd(extra=(), props=None, **changes):
            """A one-fire capture with something wrong with it."""
            shutil.rmtree(tmp / "captures" / "odd", ignore_errors=True)
            folder = tmp / "captures" / "odd" / "2019-07-10"
            fires = [incident("K10001", "2019-07-01T20:00:00Z", None, "Under Control", 1, 5)]
            fires[0]["properties"].update(props or {})
            write_capture(folder, "2019-07-11T02:00:00Z", fires + list(extra), [], **changes)
            return folder

        def build(folder):
            return season.build(season.read_raw(folder, mirror, snapshot))

        same(sorted(build(odd()))[:2], [f"{SYN}.days.json", f"{SYN}.json"],
             "the one-fire capture is sound until something is wrong with it")
        refuse(lambda: build(odd(complete=False)), "not marked complete")
        refuse(lambda: build(odd(said="2019-07-11")), "its manifest says")
        refuse(lambda: build(odd(props={"FIRE_CENTRE": 7})), "does not go with the letter")
        refuse(lambda: build(odd(props={"FIRE_OF_NOTE_IND": "Maybe"})), "neither yes nor no")
        refuse(lambda: build(odd(props={"FIRE_NUMBER": "X10001"})), "is not a fire number")
        refuse(lambda: build(odd(extra=[incident(
            "K10001", "2019-07-01T20:00:00Z", None, "Under Control", 1, 5)])), "appears twice")
        other = incident("K10002", "2019-07-01T20:00:00Z", None, "Under Control", 1, 5)
        other["properties"]["FIRE_YEAR"] = SYN - 1
        refuse(lambda: build(odd(extra=[other])), "one fire year")
        refuse(lambda: build(tmp / "nowhere"), "no MANIFEST.json")

        def edit_manifest(folder, change):
            manifest = json.loads((folder / "MANIFEST.json").read_text())
            change(manifest)
            (folder / "MANIFEST.json").write_text(json.dumps(manifest))

        folder = odd()        # a count that is not the layer's own
        edit_manifest(folder, lambda m: m["layers"]["incidents"].update(countOnly=2))
        refuse(lambda: build(folder), "do not match the layer's own count")
        folder = odd()        # a status tally that is not the layer's own
        edit_manifest(folder, lambda m: m["layers"]["incidents"].update(byStatus={"Out": 1}))
        refuse(lambda: build(folder), "do not match the layer's own count")
        folder = odd()        # dates in a zone this does not read
        layer = folder / "incidents.layer.json"
        data = layer.read_bytes().replace(b'"UTC"', b'"PST"')
        layer.write_bytes(data)
        edit_manifest(folder, lambda m: [r.update(sha256=hashlib.sha256(data).hexdigest())
                                         for r in m["requests"] if r["file"] == layer.name])
        refuse(lambda: build(folder), "will not guess")
        # a mirror day whose two halves are minutes apart
        write_mirror(tmp / "apart", [("fires", "2019-07-06T20:00:00Z", []),
                                     ("perims", "2019-07-06T20:05:00Z", [])])
        refuse(lambda: season.read_raw(capture, tmp / "apart", snapshot), "apart")
        # a mirror day with fires and no perimeters
        write_mirror(tmp / "half", [("fires", "2019-07-06T20:00:00Z", [])])
        refuse(lambda: season.read_raw(capture, tmp / "half", snapshot), "but not both")
        # a mirror copy that is not the file its index names
        write_mirror(tmp / "swapped", [("fires", "2019-07-06T20:00:00Z", []),
                                       ("perims", "2019-07-06T20:00:01Z", [])])
        (tmp / "swapped" / "20190706T200000Z" / "fires.json").write_bytes(b"{}")
        refuse(lambda: season.read_raw(capture, tmp / "swapped", snapshot),
               "not the file its manifest")
        # a mirror copy that is not in the mirror's shape
        bad = mirror_fire("K10003", "Being Held", 2, "2019-07-05T07:00:00Z")
        bad["properties"]["FIRE_OUT_DATE"] = 1
        write_mirror(tmp / "shape", [("fires", "2019-07-06T20:00:00Z", [bad]),
                                     ("perims", "2019-07-06T20:00:01Z", [])])
        refuse(lambda: season.build(season.read_raw(capture, tmp / "shape", snapshot)),
               "not in the mirror's shape")
        refuse(lambda: season.read_raw(capture, tmp / "no-such-history", snapshot),
               "no INDEX.json")
        refuse(lambda: season.read_raw(capture, None, tmp / "no-snapshot.json"),
               "the repository snapshot")
    return f"{len(refused)} inputs that are not what they say, {len(refused)} refusals"


@test
def generalisation_small_cases():
    square = [[0, 0], [0, 0.5], [0, 1], [0.5, 1], [1, 1], [1, 0.5], [1, 0], [0.5, 0], [0, 0]]
    same(season.generalise_ring(square), [[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]], "midpoints go")
    tiny = [[0, 0], [0.0001, 0.0002], [0.0003, 0.0001], [0.0002, -0.0001], [0.0001, -0.0001],
            [0, 0]]
    got = season.generalise_ring(tiny)
    same((len(got), got[0], got[-1]), (4, [0, 0], [0, 0]), "never less than a closed triangle")
    short = [[0, 0], [0, 1], [1, 1], [0, 0]]
    same(season.generalise_ring(short), short, "a ring of four points is left alone")
    bump = [[0, 0], [0, 1], [0.5, 1.0021], [1, 1], [1, 0], [0, 0]]
    same(len(season.generalise_ring(bump)), 6, "a vertex just over the tolerance stays")
    bump[2][1] = 1.0019
    same(len(season.generalise_ring(bump)), 5, "a vertex just under the tolerance goes")
    multi = {"type": "MultiPolygon", "coordinates": [[square], [square, square]]}
    same([len(poly) for poly in season.generalise(multi)["coordinates"]], [1, 2],
         "multipolygons keep their parts and their holes")
    same(season.generalise({"type": "Polygon", "coordinates": [[[0.00004, 1.23456789], [0, 2],
                                                                [1, 2], [0.00004, 1.23456789]]]}),
         {"type": "Polygon", "coordinates": [[[0.0, 1.2346], [0, 2], [1, 2], [0.0, 1.2346]]]},
         "four decimal places")
    raises(lambda: season.generalise({"type": "Point", "coordinates": [0, 0]}), "not a polygon")
    return "collinear vertices dropped, the tolerance is 0.002, a triangle kept, parts kept"


# ============================================================================================
# 3. THE RAW INPUTS, when this machine has them
# ============================================================================================
def raw_inputs():
    where = os.environ.get("SEASON_CAPTURE")
    index = load(f"{YEAR}.days.json")
    if not where:
        day = load(f"{YEAR}.json")["capture"]["localDate"]
        raise Skip(
            "SEASON_CAPTURE is not set. This test needs two folders of raw agency data that "
            f"are deliberately not in the repository: the capture folder '{day}' (complete "
            "copies of the two public layers; its MANIFEST.json has sha256 "
            f"{PINS['captureManifestSha256'][:16]}...) and the folder 'mirror-history' (the "
            "recovered copies of the live mirror; its INDEX.json has sha256 "
            f"{index['mirrorHistory']['index']['sha256'][:16]}...), looked for at "
            "../../mirror-history from the capture folder or where SEASON_MIRROR_HISTORY says. "
            "Run: SEASON_CAPTURE=<that capture folder> make seasoncheck")
    capture = pathlib.Path(where)
    assert (capture / "MANIFEST.json").is_file(), (
        f"SEASON_CAPTURE names a folder called '{capture.name}' that has no MANIFEST.json")
    mirror = os.environ.get("SEASON_MIRROR_HISTORY")
    mirror = pathlib.Path(mirror) if mirror else capture.parent.parent / "mirror-history"
    assert (mirror / "INDEX.json").is_file(), (
        f"the folder '{mirror.name}' has no INDEX.json: set SEASON_MIRROR_HISTORY")
    return capture, mirror, index["dates"][-1]


def mirror_copies(mirror, name):
    for c in json.loads((mirror / "INDEX.json").read_bytes())["copies"]:
        if c["name"] == name:
            yield c, json.loads((mirror / c["folder"] / c["file"]).read_bytes())


@test
def raw_regeneration_is_byte_for_byte():
    """python3 pipeline/season.py <capture folder>, against what is committed."""
    capture, mirror, through = raw_inputs()
    folders = load(f"{YEAR}.prov.json")["captureFolders"]
    state = season.read_raw(capture, mirror, through=through, capture_folders=folders)
    same(state["capture"]["manifest"]["sha256"], PINS["captureManifestSha256"],
         "SEASON_CAPTURE is not the pinned capture")
    files = season.build(state)
    problems = season.drift(files, YEAR, SEASON)
    assert not problems, "; ".join(problems)
    same(files, season.build(season.read_raw(capture, mirror, through=through, capture_folders=folders)), "two runs")
    committed = season.build(season.read_committed(YEAR, SEASON))
    same(sorted(committed), sorted(files), "the two ways of building agree on the files")
    same(committed, files, "the two ways of building agree on the bytes")
    return f"{len(files)} files regenerated from the raw inputs, byte for byte, twice"


@test
def raw_capture_record_ignores_new_and_refuses_missing_or_changed():
    capture, mirror, through = raw_inputs()
    folders = load(f"{YEAR}.prov.json")["captureFolders"]
    with scratch() as tmp:
        root = pathlib.Path(tmp) / "captures"
        shutil.copytree(capture.parent, root)
        selected = root / capture.name
        extra = root / "2026-10-01T235959"
        shutil.copytree(selected, extra)
        page = extra / "incidents.page-000.geojson"
        doc = json.loads(page.read_bytes())
        doc["features"][0]["properties"]["CURRENT_SIZE"] = 987654
        page.write_text(json.dumps(doc))
        state = season.read_raw(selected, mirror, through=through, capture_folders=folders)
        same(season.drift(season.build(state), YEAR, SEASON), [], "new capture is information")
        victim = root / folders[-1]["folder"]
        manifest = victim / "MANIFEST.json"
        original = manifest.read_bytes()
        manifest.write_bytes(original + b" ")
        altered = raises(lambda: season.read_raw(selected, mirror, through=through,
                         capture_folders=folders), f"capture '{victim.name}': contents changed")
        manifest.write_bytes(original)
        shutil.rmtree(victim)
        missing = raises(lambda: season.read_raw(selected, mirror, through=through,
                         capture_folders=folders), f"capture '{victim.name}': missing")
    return f"{extra.name}: not in the record; green; {altered}; {missing}"


@test
def raw_generalisation_reproduces_the_servers():
    """A capture day's perimeters are generalised here; a mirror day's were generalised by the
    server. Where both hold one perimeter at one vintage, the vertices must be identical."""
    capture, mirror, _ = raw_inputs()
    full = {}
    for f in season.read_capture(capture)["perimeters"]["features"]:
        full.setdefault(f["properties"]["FIRE_NUMBER"], []).append(f)

    def compare(features):
        """(perimeters reproduced exactly, perimeters held at the capture's vintage)."""
        verdict = {}
        for f in features:
            p = f["properties"]
            held = full.get(p["FIRE_NUMBER"], [])
            vintage = (p["TRACK_DATE"], p["FIRE_SIZE_HECTARES"])
            if len(held) != 1 or vintage != (held[0]["properties"]["TRACK_DATE"],
                                             held[0]["properties"]["FIRE_SIZE_HECTARES"]):
                continue
            exact = season.generalise(held[0]["geometry"]) == f["geometry"]
            verdict[p["FIRE_NUMBER"]] = verdict.get(p["FIRE_NUMBER"], True) and exact
        return sum(verdict.values()), len(verdict)

    served = [f for _, doc in mirror_copies(mirror, "perims") for f in doc["data"]["features"]]
    exact, total = compare(served)
    same((exact, total), (PINS["generalisation"]["mirrorHistory"],) * 2,
         "perimeters reproduced exactly, of those held at the same vintage: mirror history")
    snap = json.loads((ROOT / "data" / "snapshot.json").read_bytes())["perimeters"]["features"]
    exact2, total2 = compare(snap)
    same((exact2, total2), (PINS["generalisation"]["snapshot"],) * 2,
         "perimeters reproduced exactly, of those held at the same vintage: snapshot")
    return (f"{exact} of {total} same-vintage perimeters in the mirror history and "
            f"{exact2} of {total2} in the snapshot: identical vertices")


@test
def raw_status_days_are_the_last_copy_of_each_local_day():
    """The selection, done again here from the recovered index without the generator's code."""
    capture, mirror, _ = raw_inputs()
    last, copies = {}, 0
    for c, _ in mirror_copies(mirror, "fires"):
        copies += 1
        when = datetime.datetime.fromisoformat(c["fetchedAt"].replace("Z", "+00:00"))
        day = when.astimezone(VANCOUVER).strftime("%Y-%m-%d")
        if day not in last or when > last[day][0]:
            last[day] = (when, c)
    index = load(f"{YEAR}.days.json")
    same(copies, index["mirrorHistory"]["fireCopies"], "fires copies in the recovered history")
    got = {d["date"]: (d["fetchedAt"], d["fires"]["sha256"]) for d in index["days"]
           if d["kind"] == "mirror-history"}
    want = {day: (when.strftime("%Y-%m-%dT%H:%M:%SZ"), c["sha256"])
            for day, (when, c) in last.items() if day not in got or got[day][1] == c["sha256"]}
    superseded = sorted(set(last) - set(want))
    for day in superseded:           # a later copy of another kind took the day; it must say so
        entry = [d for d in index["days"] if d["date"] == day][0]
        assert any(x["kind"] == "mirror-history" for x in entry["source"].get(
            "supersedes", [])), f"{day}: a recovered copy was passed over and nothing says so"
    same(got, want, "mirror days")
    for day in got:
        when, c = last[day]
        same((SEASON / "days" / day / "fires.json").read_bytes(),
             (mirror / c["folder"] / c["file"]).read_bytes(), f"{day} bytes")
    return (f"{copies} copies on {len(last)} local dates; {len(got)} status days are the last "
            f"copy of their date, byte-identical; {len(superseded)} superseded by a later kind")


@test
def raw_coverage_by_every_dated_record():
    """How many of the season's fires appear in ANY dated record held, status day or not."""
    capture, mirror, _ = raw_inputs()
    listed = set()
    for _, doc in mirror_copies(mirror, "fires"):
        listed |= {f["properties"]["FIRE_NUMBER"] for f in doc["data"]["features"]}
    for d in load(f"{YEAR}.days.json")["days"]:
        listed |= {f["properties"]["FIRE_NUMBER"]
                   for f in load(d["fires"]["file"])["data"]["features"]}
    numbers = {f["fire"] for f in load(f"{YEAR}.json")["fires"]}
    got = {"fires": len(listed), "inSeasonFile": len(listed & numbers),
           "notInSeasonFile": sorted(listed - numbers), "seasonFiresInNone": len(numbers - listed)}
    same(got, PINS["everyDatedRecord"], "coverage by every dated record")
    return (f"{got['fires']} fires in some dated record, {got['inSeasonFile']} of them in the "
            f"season file; {got['seasonFiresInNone']:,} season fires in none")


def main():
    only = sys.argv[1:]
    chosen = [fn for fn in TESTS if not only or any(o in fn.__name__ for o in only)]
    failed = skipped = 0
    for fn in chosen:
        try:
            note = fn()
            print(f"  ok    {fn.__name__}" + (f": {note}" if note else ""))
        except Skip as e:
            skipped += 1
            print(f"  SKIP  {fn.__name__}\n        *** NOT RUN *** "
                  + (str(e) if skipped == 1 else "for the same reason."))
        except AssertionError as e:
            failed += 1
            print(f"  FAIL  {fn.__name__}\n        {e}")
        except Exception as e:  # noqa: BLE001  (a crash is a failure with a name)
            failed += 1
            print(f"  FAIL  {fn.__name__}\n        {type(e).__name__}: {e}")
    line = f"season: {len(chosen) - failed - skipped} passed, {failed} failed, {skipped} skipped"
    if skipped:
        line += " (raw inputs not here: SEASON_CAPTURE=<capture folder> runs those)"
    print(line)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
