/* Omitted inertia on the prescribed path. This adds no owner to the force ledger. */
import fs from 'node:fs';
import {CLASSES,MODES,PHASES,CFG,planCycle,drawAt,cycleGeometry,altAt,inducedMW} from '../../sim/index.js?v=e6a94414';
export const ADDED_MASS_COEFFICIENT = 0.70;
export const ADDED_MASS_VALUES = [ADDED_MASS_COEFFICIENT, 1.0];
export const ADDED_MASS_SOURCE = {
  assumption:'Transverse added mass of a prolate spheroid with length twice its width.',
  citation:'Lamb coefficient as tabulated by Munk, NACA Report 184.',
  localPrimarySource:false,
  localBackgroundSource:'research/papers/hochstetler-2016-heavy-lift-airships.pdf, pages 3 and 13',
  qualification:'Local research discusses added mass and cites Munk, but no local copy of NACA Report 184 was found. The numerical coefficient remains a supplied assumption; the primary source was not fetched.'
};
// Central second difference inside each phase. C1 joins have finite, one-sided acceleration.
export function accelerationAt(g,p,id,x) {
  const h=1e-4, z=Math.max(h,Math.min(1-h,x)), dt=h*p.dur[id]*60;
  return (altAt(g,p,id,z+h)-2*altAt(g,p,id,z)+altAt(g,p,id,z-h))/(dt*dt);
}
export function rotorMarginT(c,p,s) {
  const nonRotor=Object.values(s.draw).reduce((a,b)=>a+b,0)-s.draw.rotors;
  const available=Math.max(0,s.busMW-nonRotor);
  let lo=0,hi=s.thrustLimitT;
  for(let i=0;i<40;i++){
    const t=(lo+hi)/2;
    if(inducedMW(c,t*9810,s.airV,Math.max(0,-s.vz),s.led.rho,p.rotorEfficiency)>available)hi=t;else lo=t;
  }
  return Math.max(0,lo-s.owners.rotorT);
}
export function omittedInertia(c,m,p,steps=2000) {
  const g=cycleGeometry(c,p), phases=[];
  for(const [id] of PHASES){
    if(!(p.dur[id]>0))continue;
    const peaks=ADDED_MASS_VALUES.map(coefficient=>({coefficient,absT:0,worstMarginGapT:0}));
    for(let i=0;i<=steps;i++){
      const x=i/steps,s=drawAt(c,m,p,id,x),az=accelerationAt(g,p,id,x),marginT=rotorMarginT(c,p,s);
      for(const peak of peaks){
        const addedAirT=peak.coefficient*s.led.liftT;
        const forceT=(s.massT+addedAirT)*az/9.81;
        peak.worstMarginGapT=Math.max(peak.worstMarginGapT,Math.abs(forceT)-marginT);
        if(peak.progress===undefined||Math.abs(forceT)>peak.absT)Object.assign(peak,{absT:Math.abs(forceT),forceT,progress:x,accelerationMps2:az,onboardT:s.massT,addedAirT,marginT});
      }
    }
    phases.push({phase:id,peaks});
  }
  return {phases,qualification:p.feasible&&phases.some(r=>r.peaks.some(q=>q.worstMarginGapT>1e-6))?'closes only quasi-statically':p.feasible?'omitted inertia below sampled rotor margin':'does not close on the drawn hardware'};
}
if(process.argv[1]?.endsWith('energy-motion.mjs')){
  const rows=[];
  for(const c of Object.values(CLASSES))for(const km of [15,60])for(const basis of ['record','favourable']){
    const p=planCycle(c,MODES.balanced,km,null,{basis});
    rows.push({class:c.id,km,basis,feasible:p.feasible,...omittedInertia(c,MODES.balanced,p)});
  }
  const result={source:ADDED_MASS_SOURCE,coefficients:ADDED_MASS_VALUES,samplesPerPhase:2001,
    marginMeaning:'Additional downward rotor thrust at the sampled instant, holding aerodynamic force and other electrical loads fixed. Absolute omitted inertia is compared conservatively with that reserve.',
    massMeaning:'Hull dry-mass target, water and nitrogen aboard, plus coefficient times displaced local air mass. Hanging-bag dynamics are excluded.',rows};
  fs.writeFileSync('research/analysis/energy-motion.json',JSON.stringify(result,null,2)+'\n');
  let md='# Omitted vertical inertia\n\nGenerated by `node research/analysis/energy-motion.mjs`. No inertial force is assigned an owner in the current ledger.\n\n';
  md+=`${ADDED_MASS_SOURCE.assumption} The added-mass coefficients are ${ADDED_MASS_VALUES.join(' and ')}.\n\n${ADDED_MASS_SOURCE.citation} ${ADDED_MASS_SOURCE.qualification} Background: ${ADDED_MASS_SOURCE.localBackgroundSource}.\n\n`;
  md+=result.marginMeaning+'\n\n'+result.massMeaning+'\n\n';
  md+='The largest absolute inertial force in each phase is shown with the rotor reserve at that instant. The qualifier also checks all other sampled instants.\n\n';
  md+='| Class | km | Basis | Phase | Coefficient | Omitted force, t | Rotor reserve, t |\n|---|---:|---|---|---:|---:|---:|\n';
  for(const r of rows){
    for(const phase of r.phases)for(const p of phase.peaks)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${phase.phase} | ${p.coefficient.toFixed(2)} | ${p.absT.toFixed(3)} | ${(p.marginT??0).toFixed(3)} |\n`;
    console.log(r.class,r.km,r.basis,r.qualification);
  }
  md+='\n';
  for(const r of rows)md+=`- ${r.class}, ${r.km} km, ${r.basis}: ${r.qualification}.\n`;
  fs.writeFileSync('research/analysis/energy-motion.md',md);
}
