import {OPERATING_MARGIN_TEXT} from '../../sim/operating-margin.js?v=31a23fa3';
import {MISSION_QUALIFIER,DYNAMIC_PROFILE_NOTE,STORAGE_PROFILE_NOTE} from '../../sim/energy-label.js?v=31a23fa3';
import {writeGenerated} from './energy-output.mjs';
import {plantEnergyTable,COLD_READY_NOTE,plantDutyTable} from './energy-plant.mjs';
/* Human-readable tables from replayable model inputs; no slow search here. */
import fs from 'node:fs';
import {batteryMass,specificEnergies} from './energy-omissions.mjs';
import {regimeTable} from './energy-rotor-regime.mjs';
import {powerTable} from './energy-rotor-power.mjs';
import {CLASSES} from '../../sim/index.js?v=31a23fa3';
const read=n=>JSON.parse(fs.readFileSync(`research/analysis/${n}.json`));
const outputs={},emit=process.argv.includes('--emit');
const save=(path,body)=>{outputs[path]=body;if(!emit)writeGenerated(path,body);};
const necessary=read('energy-necessary');
import {storageNote} from './energy-storage-notes.mjs';
import {prescribed,documentSensitivity} from './energy-printed-profiles.mjs';
const motion=read('energy-motion');
const profileNote=b=>b.inertia.qualification+([storageNote(b)].filter(Boolean).map(n=>'; '+n).join(''));
function asDrawnNote(r){
 const q=motion.rows.find(q=>q.class===r.class&&q.km===r.km&&q.basis===r.basis);
 return [r.asDrawn.feasible&&q?.worstSignedGaps.some(q=>q.gapT>1e-6)?DYNAMIC_PROFILE_NOTE:null,
  storageNote(prescribed(r))].filter(Boolean).join('; ');
}
const f=x=>x==null?'none':x.toFixed(3);
const req=read('energy-requirements');
let md='# What the model would require\n\n'+MISSION_QUALIFIER+'\n\nGenerated by `node research/analysis/energy-tables.mjs`. Each printed closing value is rounded up to three decimals and replayed at the verdict resolution.\n\n';
md+=`| Class | km | Basis | As drawn | Minutes: drawn / kept / power pair | Water kept, t | Delivered, t | kWh/t | Required battery, MW | Rotor thrust, t | Battery mass, t (${Object.values(specificEnergies).map(v=>v.value).join(' / ')} Wh/kg) | Storage notes |\n|---|---:|---|---|---:|---:|---:|---:|---:|---:|---|---|\n`;
for(const r of req.rows){const b=r.ballast,p=r.powerAndThrust,m=p.feasible?batteryMass(CLASSES[r.class],p.requiredBatteryMW):null;
 const base=prescribed(r),notes=[storageNote(base)];
 if(b.feasible)notes.push('retained-water: '+storageNote({...base,options:{...base.options,ballastT:b.ballastT}}));
 if(p.feasible)notes.push('power pair: '+storageNote({...base,options:{...base.options,requiredBatteryMW:p.requiredBatteryMW,requiredRotorT:p.requiredRotorT}}));
 md+=`| ${r.class} | ${r.km} | ${r.basis} | ${r.baseline.feasible?'closes':'does not close'} | ${f(r.baseline.cycleMin)} / ${b.feasible?f(b.cycleMin):'none'} / ${p.feasible?f(p.verification.cycleMin):'none'} | ${b.feasible?f(b.ballastT):'none'} | ${b.feasible?f(b.deliveredT):'none'} | ${b.feasible?f(b.kwhPerTonne):'none'} | ${p.feasible?f(p.requiredBatteryMW):'none'} | ${p.feasible?f(p.requiredRotorT):'none'} | ${m?Object.values(m.cases).map(v=>f(v.tonnes)+(v.exceedsDryTarget?' (exceeds dry target)':'')).join(' / '):'none'} | ${notes.filter(Boolean).join('; ')} |\n`;
}
md+='\nCycle minutes are printed separately for the prescribed profile, retained-water requirement and power-and-thrust requirement.\n';
md+='\nThe battery masses retain each class\'s energy-to-peak-power ratio. Power alone does not fix storage mass. These are requirements, never equipment options.\n\n';
md+='Specific energies and their source qualifications bind to `research/analysis/mass-budget.json`. Values that exceed the entire dry-mass target are marked.\n\n';
md+='The bag counts when the cable carries water; the hoist remains priced. Delaying force credit until hoisting finishes changes the retained-water requirement as follows.\n\n';
md+='| Class | km | Basis | Extra water kept under stricter rule, t |\n|---|---:|---|---:|\n';
for(const r of read('energy-bag-comparison').rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${f(r.extraRetainedT)} |\n`;
md+='\n## Broadside-drag range\n\nEach entry gives the signed worst unheld force in tonnes and the feasibility verdict. Negative force needs upward authority, which is unavailable.\n\n';
const cds=req.rows[0].dragSensitivity.map(v=>v.verticalCd);
md+=`| Class | km | Basis | ${cds.map(v=>`Coefficient ${v}`).join(' | ')} |\n|---|---:|---|${cds.map(()=>'---').join('|')}|\n`;
for(const r of req.rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${r.dragSensitivity.map(v=>`${f(v.worst.unheldT)}; ${v.feasible?'closes':'does not close'}; ${storageNote({...prescribed(r),options:{basis:r.basis,verticalCd:v.verticalCd}})}`).join(' | ')} |\n`;
md+='\n## Rotor-efficiency range\n\n';
const rotor=read('energy-rotor-range');
md+=rotor.assumption+' '+rotor.regimes+'\n\n';
md+='| Class | km | Basis | Efficiency | Static thrust cap over local densities, t | Worst unheld force, t | Verdict | Storage note |\n|---|---:|---|---:|---|---:|---|---|\n';
for(const r of rotor.rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${r.rotorEfficiency} | ${f(r.thrustCapMinT)} to ${f(r.thrustCapMaxT)} | ${f(r.worstUnheldT)} | ${r.feasible?'closes':'does not close'} | ${storageNote({...prescribed(r),options:{basis:r.basis,rotorEfficiency:r.rotorEfficiency}})} |\n`;
save('research/analysis/energy-requirements.md',md);
for(const name of ['energy-profiles','energy-feasible']){
 const data=read(name);
 let out='# Feasible simulated profiles\n\n<!-- profile-tables:start -->\n'+MISSION_QUALIFIER+'\n\nGenerated by `node research/analysis/energy-tables.mjs`. Each printed row replays through `planCycle`; no aircraft has flown.\n\n';
 out+=COLD_READY_NOTE+'\n\n';
 if(data.distanceSelection){const d=data.distanceSelection;out+=`Pinned exercise allocator distances: minimum ${f(d.min)}, median ${f(d.median)}, maximum ${f(d.max)} km. ${d.reason} Source: ${d.source} Re-run: \`${d.capture.rerun}\`.\n\n`;}
 out+=`The search uses speed multipliers ${data.space.speedMultipliers.join(', ')} and independent vertical controls ${JSON.stringify(data.space.verticalProfile)} in all three modes.\n\n`;
 out+='Retained water uses five-percent payload steps plus each bisected first reserve-closing threshold. The result is the cheapest eligible profile found in the stated space.\n\n'+OPERATING_MARGIN_TEXT+'\n\n';
 out+='Profile quantities assume a hull that floats in the flight model; they do not establish structural float closure.\n\n';
 out+='| Class | km | Basis | Mode | Speed | Climb / letdown rate, m/s; airspeed, m/s | Water kept, t | Delivered, t | Minutes | MWh | kWh/t | Signed gap tf / direction (coefficient 0.70) | Qualification |\n|---|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---|---|\n';
 for(const r of data.rows){const a=r.asDrawn;out+=`| ${r.class} | ${r.km} | ${r.basis} | as drawn: ${a.feasible?'closes':'does not close'} | 1 | prescribed | ${f(a.ballastT)} | ${f(a.deliveredT)} | ${f(a.cycleMin)} | ${f(a.cycleMWh)} | ${f(a.kwhPerTonne)} | | ${asDrawnNote(r)} |\n`;const b=r.best;if(!b){out+=`| ${r.class} | ${r.km} | ${r.basis} | none in the stated space | | | | | | | | | |\n`;continue;}
 const inert=b.inertia.worstSignedGaps[0];
 out+=`| ${r.class} | ${r.km} | ${r.basis} | ${b.mode} | ${b.options.speedMultiplier} | ${b.options.verticalProfile?Object.values(b.options.verticalProfile).join(' / '):'prescribed'} | ${f(b.options.ballastT)} | ${f(b.deliveredT)} | ${f(b.cycleMin)} | ${f(b.cycleMWh)} | ${f(b.kwhPerTonne)} | ${f(inert.gapT)} / ${inert.direction} | ${profileNote(b)} |\n`;
 }
 out+='\n## Full delivery where found\n\nThe following full-payload profiles can cost more per tonne than the selected row. They are not global minima.\n\n'+MISSION_QUALIFIER+'\n\n';
 if(!data.rows.some(r=>r.fullDeliveryBest))out+='No full-payload profile meets the control reserve target in this stated search. Physically closing diagnostics are not served without reserve.\n\n';
 out+='| Class | km | Basis | Mode | Minutes | MWh | kWh/t | Signed gap tf / direction (coefficient 0.70) | Inertia qualification |\n|---|---:|---|---|---:|---:|---:|---|---|\n';
 for(const r of data.rows){const b=r.fullDeliveryBest;if(b){const inert=b.inertia.worstSignedGaps[0];out+=`| ${r.class} | ${r.km} | ${r.basis} | ${b.mode} | ${f(b.cycleMin)} | ${f(b.cycleMWh)} | ${f(b.kwhPerTonne)} | ${f(inert.gapT)} / ${inert.direction} | ${profileNote(b)} |\n`;}}
 out+='\n## Coefficient ranges for each selected feasible profile\n\nEach row replays the same printed controls; a coefficient change can make it infeasible.\n\n'+MISSION_QUALIFIER+'\n\n';
 out+='| Class | km | Basis | Profile | Parameter | Value | Verdict | Worst unheld, t | Minutes | MWh | Storage note |\n|---|---:|---|---|---|---:|---|---:|---:|---:|---|\n';
 for(const r of data.rows)for(const b of [r.best,r.fullDeliveryBest].filter(Boolean))for(const s of b.sensitivity||[])out+=`| ${r.class} | ${r.km} | ${r.basis} | ${b===r.best?'cheapest found':'full delivery'} | ${s.parameter} | ${s.value} | ${s.feasible?'closes':'does not close'} | ${f(s.worst.unheldT)} | ${f(s.cycleMin)} | ${f(s.cycleMWh)} | ${storageNote({...b,options:{...b.options,[s.parameter]:s.value}})} |\n`;
 out+='\nThe signed screen checks every phase against simultaneous authority in both directions. The full per-phase signed demands at coefficients 0.70 and 1.00 are in the matching JSON. This is a hull-only sampled diagnostic, not dynamic validation. The fleet replays its selected controls at each mission’s exact inputs; this table does not promise interpolation.\n';
 out+=regimeTable(name);
 out+=powerTable(name);
 out+=plantEnergyTable(name);
 out+=plantDutyTable(name);
 out+='\n<!-- profile-tables:end -->\n';
 save(`research/analysis/${name}.md`,out);
}
if(emit)console.log(JSON.stringify(outputs));
else console.log((process.argv.includes('--check')?'Checked':'Wrote')+' requirements, baseline profile search and allocator-distance feasible tables.');
