/* Human-readable tables from replayable model inputs; no slow search here. */
import fs from 'node:fs';
import {batteryMass,specificEnergies} from './energy-omissions.mjs';
import {CLASSES} from '../../sim/index.js';
const read=n=>JSON.parse(fs.readFileSync(`research/analysis/${n}.json`));
const f=x=>x==null?'none':x.toFixed(3);
const req=read('energy-requirements');
let md='# What the model would require\n\nGenerated by `node research/analysis/energy-tables.mjs`. Each printed closing value is rounded up to three decimals and replayed at the verdict resolution.\n\n';
md+=`| Class | km | Basis | Water kept, t | Delivered, t | kWh/t | Required battery, MW | Rotor thrust, t | Battery mass, t (${Object.values(specificEnergies).map(v=>v.value).join(' / ')} Wh/kg) |\n|---|---:|---|---:|---:|---:|---:|---:|---|\n`;
for(const r of req.rows){const b=r.ballast,p=r.powerAndThrust,m=p.feasible?batteryMass(CLASSES[r.class],p.requiredBatteryMW):null;
 md+=`| ${r.class} | ${r.km} | ${r.basis} | ${b.feasible?f(b.ballastT):'none'} | ${b.feasible?f(b.deliveredT):'none'} | ${b.feasible?f(b.kwhPerTonne):'none'} | ${p.feasible?f(p.requiredBatteryMW):'none'} | ${p.feasible?f(p.requiredRotorT):'none'} | ${m?Object.values(m.cases).map(v=>f(v.tonnes)+(v.exceedsDryTarget?' (exceeds dry target)':'')).join(' / '):'none'} |\n`;
}
md+='\nThe battery masses retain each class\'s energy-to-peak-power ratio. Power alone does not fix storage mass. These are requirements, never equipment options.\n\n';
md+='Specific energies and their source qualifications bind to `research/analysis/mass-budget.json`. Values that exceed the entire dry-mass target are marked.\n\n';
md+='The bag counts when the cable carries water; the hoist remains priced. Delaying force credit until hoisting finishes changes the retained-water requirement as follows.\n\n';
md+='| Class | km | Basis | Extra water kept under stricter rule, t |\n|---|---:|---|---:|\n';
for(const r of read('energy-bag-comparison').rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${f(r.extraRetainedT)} |\n`;
md+='\n## Broadside-drag range\n\nEach entry gives the signed worst unheld force in tonnes and the feasibility verdict. Negative force needs upward authority, which is unavailable.\n\n';
const cds=req.rows[0].dragSensitivity.map(v=>v.verticalCd);
md+=`| Class | km | Basis | ${cds.map(v=>`Coefficient ${v}`).join(' | ')} |\n|---|---:|---|${cds.map(()=>'---').join('|')}|\n`;
for(const r of req.rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${r.dragSensitivity.map(v=>`${f(v.worst.unheldT)}; ${v.feasible?'closes':'does not close'}`).join(' | ')} |\n`;
md+='\n## Rotor-efficiency range\n\n';
const rotor=read('energy-rotor-range');
md+=rotor.assumption+' '+rotor.regimes+'\n\n';
md+='| Class | km | Basis | Efficiency | Static thrust cap over local densities, t | Worst unheld force, t | Verdict |\n|---|---:|---|---:|---|---:|---|\n';
for(const r of rotor.rows)md+=`| ${r.class} | ${r.km} | ${r.basis} | ${r.rotorEfficiency} | ${f(r.thrustCapMinT)} to ${f(r.thrustCapMaxT)} | ${f(r.worstUnheldT)} | ${r.feasible?'closes':'does not close'} |\n`;
fs.writeFileSync('research/analysis/energy-requirements.md',md);
for(const name of ['energy-profiles','energy-feasible']){
 const data=read(name);
 let out='# Feasible simulated profiles\n\nGenerated by `node research/analysis/energy-tables.mjs`. Each printed row replays through `planCycle`; no aircraft has flown.\n\n';
 if(data.distanceSelection){const d=data.distanceSelection;out+=`Golden allocator distances: minimum ${f(d.min)}, median ${f(d.median)}, maximum ${f(d.max)} km. ${d.reason}\n\n`;}
 out+=`The search uses speed multipliers ${data.space.speedMultipliers.join(', ')} and vertical-rate multipliers ${data.space.verticalRateMultipliers.join(', ')} in all three modes.\n\n`;
 out+='Retained water uses five-percent payload steps plus each bisected first closing threshold. The reported profile has the lowest energy per delivered tonne found in this sampled space.\n\n';
 out+='| Class | km | Basis | Mode | Speed | Vertical rate | Water kept, t | Delivered, t | Minutes | MWh | kWh/t | Largest omitted inertia / rotor reserve, t (coefficient 0.70) | Qualification |\n|---|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---|---|\n';
 for(const r of data.rows){const b=r.best;if(!b){out+=`| ${r.class} | ${r.km} | ${r.basis} | none in the stated space | | | | | | | | | |\n`;continue;}
 const inert=b.inertia.phases.map(p=>p.peaks[0]).reduce((a,b)=>a.absT>b.absT?a:b);
 out+=`| ${r.class} | ${r.km} | ${r.basis} | ${b.mode} | ${b.options.speedMultiplier} | ${b.options.verticalRateMultiplier} | ${f(b.options.ballastT)} | ${f(b.deliveredT)} | ${f(b.cycleMin)} | ${f(b.cycleMWh)} | ${f(b.kwhPerTonne)} | ${f(inert.absT)} / ${f(inert.marginT)} | ${b.inertia.qualification} |\n`;
 }
 out+='\nThe qualification compares every phase, including phases with less inertia but less reserve. The full per-phase inertia bounds at coefficients 0.70 and 1.0 are in the matching JSON. The fleet has not yet been bound to this table.\n';
 fs.writeFileSync(`research/analysis/${name}.md`,out);
}
console.log('Wrote requirements, baseline profile search and allocator-distance feasible tables.');
