import {writeGenerated} from './energy-output.mjs';
/* Every phase with unheld vertical force, on the unchanged prescribed profile. */
import fs from 'node:fs';
import {CLASSES,MODES,PHASES,planCycle,drawAt,FORCE_TOL,LIMIT_STEPS} from '../../sim/index.js?v=93744380';
export function unheldRows(){
 const rows=[];
 for(const c of Object.values(CLASSES))for(const km of [15,60])for(const basis of ['record','favourable']){
  const p=planCycle(c,MODES.balanced,km,null,{basis}),phases=[];let elapsedMin=0;
  for(const [phase] of PHASES){
   const peak=p.phasePeaks[phase],progress=peak.progress;
   const s=drawAt(c,MODES.balanced,p,phase,progress);
   if(Math.abs(s.unheldT)>FORCE_TOL*Math.max(1,Math.abs(s.surplusT)))
     phases.push({...peak,secondsIntoPhase:progress*p.dur[phase]*60,cycleMinute:elapsedMin+progress*p.dur[phase],airspeedMps:s.airV,verticalSpeedMps:s.vz});
   elapsedMin+=p.dur[phase];
  }
  rows.push({class:c.id,km,basis,profile:'as drawn',mode:'balanced',feasible:p.feasible,cycleMin:p.cycleMin,phases});
 }
 return {meaning:'Largest absolute signed unheld force in each failing phase, using the verdict mesh, refined extrema and both sides of seams from cycleLimits. Positive is unsupported surplus lift; negative requires unavailable upward authority.',samplesPerPhase:LIMIT_STEPS+1,rows};
}
const result=unheldRows();
writeGenerated('research/analysis/energy-unheld.json',JSON.stringify(result,null,2)+'\n');
let md='# Where the prescribed hull is unheld\n\nGenerated by `node research/analysis/energy-unheld.mjs`. '+result.meaning+'\n\n';
md+='| Class | km | Basis | Profile | Phase | Signed unheld, t | Progress | Cycle minute | Airspeed, m/s | Vertical speed, m/s | Limits |\n|---|---:|---|---|---|---:|---:|---:|---:|---:|---|\n';
for(const r of result.rows){
 if(!r.phases.length)md+=`| ${r.class} | ${r.km} | ${r.basis} | as drawn | no unheld phase | 0 | | | | | |\n`;
 for(const s of r.phases)md+=`| ${r.class} | ${r.km} | ${r.basis} | as drawn | ${s.phase} | ${s.unheldT.toFixed(3)} | ${s.progress.toFixed(6)} | ${s.cycleMinute.toFixed(3)} | ${s.airspeedMps.toFixed(3)} | ${s.verticalSpeedMps.toFixed(3)} | ${s.limits.join(', ')} |\n`;
}
md+='\nThe cheapest feasible profiles found in the stated space, including their minutes and delivery, are in [the profile table](energy-profiles.md).\n';
writeGenerated('research/analysis/energy-unheld.md',md);
console.log(`Generated ${result.rows.length} prescribed rows and ${result.rows.reduce((n,r)=>n+r.phases.length,0)} unheld phase records.`);
