/* Recompute comparisons and requirements; historical columns are an immutable capture
 * of HEAD before energy.patch and the applied energy index. */
import fs from 'node:fs';
import {CLASSES,MODES,planCycle,energySummary,closureRequirements} from '../../sim/index.js?v=acbad6ee';
const historical=JSON.parse(fs.readFileSync('research/analysis/energy-closure-history.json'));
const rows=[];
for(const old of historical)for(const basis of ['record','favourable']){
 const c=CLASSES[old.class],p=planCycle(c,MODES.balanced,old.km,null,{basis});
 const requirements=closureRequirements(c,MODES.balanced,old.km,basis);
 rows.push({...old,basis,current:energySummary(c,p),requirements});
 console.log(`${old.class}/${old.km}/${basis}: ${p.eCycleMWh.toFixed(6)} MWh, feasible=${p.feasible}, worst=${p.worst.unheldT.toFixed(6)} t in ${p.worst.phase}`);
}
const result={mode:'balanced',wind:'still air',clMax:1,clSensitivity:[.5,1,1.5],
 warning:'An infeasible row is supplied effort along an unsupported profile, not a flyable cycle or demonstrated delivery.',rows};
fs.writeFileSync('research/analysis/energy-closure.json',JSON.stringify(result,null,2)+'\n');
const attribution=JSON.parse(fs.readFileSync('research/analysis/energy-model-change.json'));
attribution.closure7f={reason:'Replace unowned hold/share with limited, priced force owners; whole-bus reservation; instantaneous drag; paid anchor inventory; seam-inclusive constraints.',
 steps:rows.map(r=>({class:r.class,km:r.km,basis:r.basis,firstBuilderMWh:r.first.cycleMWh,closureMWh:r.current.cycleMWh,deltaMWh:r.current.cycleMWh-r.first.cycleMWh,feasible:r.current.feasible}))};
fs.writeFileSync('research/analysis/energy-model-change.json',JSON.stringify(attribution,null,2)+'\n');
const f=(x,n=3)=>x===null||x===undefined?'—':x.toFixed(n);
const md=['# Energy closure — 2026-10-01','',
 'Generated by `node research/analysis/energy-close.mjs` from the one model. Balanced mode, still air. No vehicle flew.',
 '', '**INFEASIBLE means the drawn cycle cannot be flown under these assumptions. Its energy and battery-hours quotient price only supplied effort along that unsupported profile; they do not establish delivery or endurance.**',
 '', 'Record basis permits the bag and rotors, with signed vertical drag. Favourable basis also permits minimum-power aerodynamic hold-down, using unverified C_L,max = 1, capsule planform area, span equal to hull diameter and e = 1. The same momentum law, bus, geometry and inventory apply to both.',
 '', 'The existing class record has no independent blade thrust rating. The model uses hover thrust at its existing battery-plus-generator rating as an **unverified installed-thrust surrogate**, separate from instantaneous bus availability. Broadside vertical C_D = 1 is also unverified. Force closure here is quasi-static along the prescribed trajectory; acceleration and the opposite-flow rotor regime are not validated.',
 '', '## Old published → earlier model → closure', '', 'Old and earlier-model columns had an unpriced aerodynamic share and no feasibility verdict. Their “peak” is the figure those versions published, not a corrected extremum.', '',
 '| Class | km | basis | cycle MWh (old → first → closure) | kWh/planned tonne | peak rotor MW | battery hours quotient | current feasible | binding limits |',
 '|---|---:|---|---|---|---|---|---|---|'];
for(const r of rows)md.push(`| ${r.class} | ${r.km} | ${r.basis} | ${['old','first','current'].map(k=>f(r[k].cycleMWh)).join(' → ')} | ${['old','first','current'].map(k=>f(r[k].kwhPerTonne)).join(' → ')} | ${['old','first','current'].map(k=>f(r[k].peakRotorMW)).join(' → ')} | ${['old','first','current'].map(k=>f(r[k].hoursOnBattery)).join(' → ')} | ${r.current.feasible?'yes':'INFEASIBLE'} | ${r.current.bindingLimits.join(', ')||'none'} |`);
md.push('', '## Requirements, one lever at a time', '',
 'Retained lake-water ballast replaces delivered water; the hull and class constants are unchanged. The first feasible 1%-payload bracket is bisected. This is a verified closing value, not a proof of global minimality. The power/thrust pair holds ballast at zero and is re-evaluated by the same model, using extrema plus 1e-9 numerical headroom. A larger bus alone does not supply a missing upward actuator.', '',
 '| Class | km | basis | retained t | delivered t | kWh/t with ballast | ballast feasible | required battery MW | required downward thrust tf | power/thrust feasible |',
 '|---|---:|---|---:|---:|---:|---|---:|---:|---|');
for(const r of rows){const b=r.requirements.ballast,p=r.requirements.powerAndThrust;md.push(`| ${r.class} | ${r.km} | ${r.basis} | ${f(b.ballastT)} | ${f(b.deliveredT)} | ${f(b.kwhPerTonne)} | ${b.feasible?'yes':'no — '+b.reason} | ${f(p.requiredBatteryMW)} | ${f(p.requiredRotorT)} | ${p.feasible?'yes':'no — '+p.verification.bindingLimits.join(', ')} |`);}
md.push('', 'The instantaneous bus adds the actual solar and nitrogen-return channels to the required battery rating. The paired rating is a requirement, not a proposed powerplant. `research/analysis/air-ballast.md` retracts air admission: permanently sealed cells provide no repeatable air-ballast mechanism. Its historical energy subtraction is not a closing cycle and is not extended here.', '', '## C_L,max sensitivity', '', '| Class | km | basis | C_L,max | cycle MWh | feasible | worst unheld t | limit |', '|---|---:|---|---:|---:|---|---:|---|');
for(const r of rows)for(const s of r.requirements.clSensitivity)md.push(`| ${r.class} | ${r.km} | ${r.basis} | ${s.clMax} | ${f(s.cycleMWh)} | ${s.feasible?'yes':'INFEASIBLE'} | ${f(s.worst.unheldT)} | ${s.bindingLimits.join(', ')||'none'} |`);
md.push('', 'No measured hull C_L,max was found in the existing research. These three values are assumptions, not tests. A favourable infeasible row can consume more than the record row because it supplies more of the missing hold-down. Comparing clipped energy totals alone is not an efficiency claim.', '');
fs.writeFileSync('docs/ENERGY-CLOSURE-2026-10.md',md.join('\n'));
