import {writeGenerated} from './energy-output.mjs';
import {storageNote} from './energy-storage-notes.mjs';
import {prescribed} from './energy-printed-profiles.mjs';
/* Render the current descent reading. The older prose remains dated history. */
import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync('research/analysis/descent.json'));
const f=(v,n=3)=>v==null?'none':v.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n});
let md='# What the prescribed descent costs\n\nGenerated by `node research/analysis/energy-descent.mjs` after the browser model regenerates `descent.json`. No aircraft has flown.\n\n';
md+='These supplied-effort comparisons do not establish delivery or savings. Every listed prescribed cycle is unsupported; the force verdict decides what the model can claim.\n\n';
md+='| Class | Basis | Minutes | Letdown MWh | Letdown % of supplied effort | Peak rotor MW | Clipped minutes | Verdict | Storage note |\n|---|---|---:|---:|---:|---:|---:|---|---|\n';
for(const basis of ['record','favourable'])for(const [id,r] of Object.entries(data[basis==='record'?'classes':'favourableClasses']))
 md+=`| ${id} | ${basis} | ${f(r.cycleMin)} | ${f(r.letdown.mwh)} | ${f(r.letdown.pctOfCycle,1)} | ${f(r.letdown.peakRotorMW)} | ${f(r.letdown.clippedMinutes,2)} | ${r.feasible?'closes':'does not close'} | ${storageNote(prescribed({class:id,km:data.generated.worked.oneWayKm,basis}))} |\n`;
md+='\n| Class | Basis | Last failed altitude in static scan, m AGL | Bag-credit change, % | Bare-bag supplied-effort change per planned tonne, % | Requested delivery change, t | Storage notes: baseline / bag removed / credit disabled |\n|---|---|---:|---:|---:|---:|---|\n';
for(const basis of ['record','favourable'])for(const [id,r] of Object.entries(data[basis==='record'?'classes':'favourableClasses']))
 md+=`| ${id} | ${basis} | ${f(r.geometry.rotorsAloneFailBelowAglM,0)} | ${f(r.rotorsBlindToTheBag.creditSavesPctOfCycle,1)} | ${f(r.withoutTheBag.bagCostsPerTonnePct,1)} | ${f(r.withoutTheBag.bagBuysDeliveredT,1)} | ${[{}, {hardware:{anchorBagT:0}}, {drawOptions:{anchorCredit:false}}].map(change=>storageNote({...prescribed({class:id,km:data.generated.worked.oneWayKm,basis}),...change})).join(" / ")} |\n`;
md+='\nThe static scan ends at its stated ceiling and is not a proof of the crossing altitude. The phase ledger uses local density and instantaneous available power.\n\n';
md+='The bag comparison removes its credited force or its hardware from the same requested cycle. Retained water is not silently increased to make the comparison close.\n\n';
md+='Earlier figures remain in [the dated document record](energy-document-history.json). Current feasible profiles and minutes are in [the profile table](energy-profiles.md).\n';
writeGenerated('research/analysis/descent.md',md);
console.log('Generated both-basis descent tables from the browser record.');
