#!/usr/bin/env python3
"""Which assumptions actually move the answer. Measured, not asserted."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _style import *          # noqa
import matplotlib.pyplot as plt

# P-10000 at 15 km, each constant moved +-20%. Regenerated by tools/sensitivity_dump.js;
# the values live in figures.json so this file types none of them.
S = figures()['sensitivity']
rows = sorted(S.items(), key=lambda kv: max(abs(kv[1]['lo']), abs(kv[1]['hi'])))

fig, ax = plt.subplots(figsize=(6.4, 3.4))
for i, (name, v) in enumerate(rows):
    lo, hi = v['lo'], v['hi']
    ax.barh(i, lo, height=0.62, color=COOL, edgecolor='none')
    ax.barh(i, hi, height=0.62, color=ACCENT, edgecolor='none')
    if max(abs(lo), abs(hi)) < 0.05:
        # A measured zero is a finding — four of these constants move the headline by nothing
        # at all — so it is written out rather than left as an empty row someone reads as
        # missing data.
        ax.text(0.7, i, 'no effect', va='center', ha='left', fontsize=7.2, color=FAINT,
                fontstyle='italic')
    for val in (lo, hi):
        if abs(val) >= 0.35:
            ax.text(val + (0.55 if val > 0 else -0.55), i, f'{val:+.1f}%', va='center',
                    ha='left' if val > 0 else 'right', fontsize=7.2, color=MUTED)
ax.axvline(0, color=MUTED, lw=0.9)
ax.set_yticks(range(len(rows)))
ax.set_yticklabels([f'$\\mathtt{{{n}}}$'.replace('_', r'\_') for n, _ in rows], fontsize=8.0)
ax.set_xlabel('change in energy per cycle when the constant moves $\\pm$20%')
ax.set_xlim(-24, 34)
bare(ax, left=False)
handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in (COOL, ACCENT)]
ax.legend(handles, ['constant $-$20%', 'constant $+$20%'], loc='lower right', fontsize=7.6,
          handlelength=0.9, handleheight=0.9)
save(fig, 'sensitivity')
