#!/usr/bin/env python3
"""Record every changed closure leaf against the captured pre-correction records."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEFORE = ROOT / 'research/validation/closure-before.json'
AUDIT = ROOT / 'docs/audit/26-10-05-closure.md'


def projection(data):
    return {cid: {case: {key: row[key] for key in ('hullThatCloses', 'cellular')}
                  for case, row in hull['rightSized'].items()}
            for cid, hull in data['classes'].items()}


def leaves(data, path=''):
    if isinstance(data, dict):
        return {k: v for name, child in data.items() for k, v in leaves(child, path+'/'+name).items()}
    return {path: data}


def render():
    old = leaves(json.loads(BEFORE.read_text()))
    current = json.loads((ROOT/'research/analysis/mass-budget.json').read_text())
    new = leaves(projection(current))
    lines = ['# Closure correction, 2026-10-05', '',
             'This is a dated correction record. Earlier figures below are superseded, not current float results.',
             'The [float ledger](../FLOAT-LEDGER.md) owns the drawn-hull figures; none changed here.', '',
             'The resized equipment budget omitted sundries on the shell. The complete bill now',
             'charges the same fraction on shell and equipment, with payload separate.',
             'These conditional sizes balance a model bill; they do not validate a structure.', '',
             'Generated by `tools/gen_closure_audit.py` from `research/validation/closure-before.json`',
             'and the current `mass-budget.json`. The capture predates this correction on the same tree.', '',
             '| Record field | Old | New | Reason |', '|---|---|---|---|']
    for path in sorted(old.keys() | new.keys()):
        if old.get(path) == new.get(path):
            continue
        a = json.dumps(old[path], ensure_ascii=False) if path in old else 'absent'
        b = json.dumps(new[path], ensure_ascii=False) if path in new else 'absent'
        lines.append(f'| `{path}` | {a} | {b} | Include shell sundries; refuse cases at or above the effective wall. |')
    lines += ['', '| Published wall or margin | Old | New | Reason |', '|---|---:|---:|---|']
    rho = current['classes']['P100']['shellDensityWallKgPerM3']
    for case, row in current['classes']['P100']['rightSized'].items():
        lines.append(f"| {case} closure wall, kg/m³ | {rho:.6f} | {row['closureWallKgPerM3']:.6f} | ρ/(1 + f), using its own sundries fraction. |")
    wall = current['classes']['P100']['rightSized']['floor']['closureWallKgPerM3']
    for phi in (.74,.85,1.):
        lines.append(f'| Floor packing wall φ={phi}, kg/m³ | {rho*phi:.3f} | {wall*phi:.3f} | ρφ/(1 + f). |')
    lines += [f'| Jenett margin below the floor closure wall | 47% | {100*(1-.508/wall):.1f}% | Compare against closure, not just lift. |',
              f'| 0.75 allowance margin | 22% | {100*(1-.75/wall):.1f}% | Same corrected wall. |',
              f'| Metlen ≈0.94 verdict | passes by 2% | fails closure by {100*(.94/wall-1):.1f}% | Still passes the lift wall. |',
              '| Reference volume headline | about 2.1× | 2.35× | 516,827 / 220,000, with shell sundries. |',
              '| Floor sundries prose | 5% | 10% | Match the already committed model input; the input did not change. |', '']
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--capture', type=Path, help='capture original JSON once, before changing its records')
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    if args.capture:
        if BEFORE.exists():
            ap.error('the original capture is immutable')
        BEFORE.write_text(json.dumps(projection(json.loads(args.capture.read_text())), indent=2)+'\n')
    text = render()
    if args.check:
        if AUDIT.read_text() != text:
            print('closure audit differs from current records')
            return 1
    else:
        AUDIT.write_text(text)
    print('closure audit: every changed closure leaf recorded')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
