/* Candidate controls from generated energy records. No interpolation or cached verdict. */
import fs from 'node:fs';
import crypto from 'node:crypto';
const files=['sim/config.js','sim/atmosphere.js','sim/physics.js','sim/power.js','sim/profile.js','sim/plan.js','sim/requirements.js'];
const strip=s=>s.replace(/(\.m?js)\?v=[A-Za-z0-9_.-]+(['"])/g,'$1$2');
const hashes=Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(strip(fs.readFileSync(file,'utf8'))).digest('hex')]));
const pool={P100:[],P1000:[],P10000:[]};
for(const file of ['research/analysis/energy-profiles.json','research/analysis/energy-feasible.json']){
 const data=JSON.parse(fs.readFileSync(file));
 for(const row of data.rows)for(const [kind,profile] of [['best',row.best],['fullDeliveryBest',row.fullDeliveryBest]]){
  if(!profile)continue;
  const {basis,...options}=profile.options;
  const controls={mode:profile.mode,options};
  if(pool[row.class].some(p=>JSON.stringify(p.controls)===JSON.stringify(controls)))continue;
  pool[row.class].push({controls,source:{file,class:row.class,km:row.km,basis:row.basis,key:kind}});
 }
}
const body='/* Generated by tools/gen_served_candidates.mjs; controls only, no mission verdicts. */\n'+
 'export const MODEL_SOURCE_HASHES = '+JSON.stringify(hashes,null,2)+';\n'+
 'export const SERVED_CANDIDATES = '+JSON.stringify(pool,null,2)+';\n';
const outputs={'sim/served-candidates.js':body};
if(process.argv.includes('--emit'))console.log(JSON.stringify(outputs));
else if(process.argv.includes('--check')){
 const stale=Object.entries(outputs).filter(([f,v])=>!fs.existsSync(f)||fs.readFileSync(f,'utf8')!==v);
 if(stale.length){console.error('FAIL served candidates: '+stale.map(([f])=>f).join(', '));process.exitCode=1;}
 else console.log('PASS served candidates: record-derived controls and model source hashes are fresh');
}else{for(const [f,v] of Object.entries(outputs))fs.writeFileSync(f,v);console.log('Generated served candidate controls: '+Object.entries(pool).map(([id,p])=>id+'='+p.length).join(', '));}
