/* Candidate controls from generated energy records. No interpolation or cached verdict. */
import fs from 'node:fs';
import crypto from 'node:crypto';
import {CLASSES,MODES,planCycle} from '../sim/index.js';
const files=['research/analysis/fleet-route-control-seeds.json','sim/config.js','sim/atmosphere.js','sim/physics.js','sim/power.js','sim/profile.js','sim/plan.js','sim/wind.js','sim/requirements.js','sim/operating-margin.js'];
const strip=s=>s.replace(/(\.m?js)\?v=[A-Za-z0-9_.-]+(['"])/g,'$1$2');
const hashes=Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(strip(fs.readFileSync(file,'utf8'))).digest('hex')]));
const pool={P100:[],P1000:[],P10000:[]};
for(const file of ['research/analysis/energy-profiles.json','research/analysis/energy-feasible.json']){
 const data=JSON.parse(fs.readFileSync(file));
 for(const row of data.rows)for(const [kind,profile] of [['best',row.best],['fullDeliveryBest',row.fullDeliveryBest]]){
  if(!profile)continue;
  const {basis,...options}=profile.options;
  const controls={mode:profile.mode,options};
  if(pool[row.class].some(p=>JSON.stringify(p.controls)===JSON.stringify(controls)))continue;
  pool[row.class].push({controls,source:{file,class:row.class,km:row.km,basis:row.basis,key:kind}});
 }
}
// A changed quantile search can drop controls still needed between its sample points.
// Keep the explicitly pinned BASE controls; every route still gets exact replay.
const seedFile='research/analysis/fleet-route-control-seeds.json';
const seeds=JSON.parse(fs.readFileSync(seedFile));
for(const [index,row] of seeds.rows.entries()){
 const options={...row.options,basis:'record'};
 if(options.requiredBatteryMW!==undefined||options.requiredRotorT!==undefined)
  throw new Error('FLEET_ROUTE_SEED_INVALID: seed changes drawn hardware');
 const p=planCycle(CLASSES[row.class],MODES[row.mode],row.km,null,options);
 if(!p.feasible||!(p.deliveredT>0))throw new Error('FLEET_ROUTE_SEED_INVALID: stored route no longer closes');
 const controls={mode:row.mode,options:row.options};
 if(!pool[row.class].some(p=>JSON.stringify(p.controls)===JSON.stringify(controls)))
  pool[row.class].push({controls,source:{file:seedFile,class:row.class,km:row.km,basis:'record',key:'rows['+index+']'}});
}
const body='/* Generated by tools/gen_served_candidates.mjs; controls only, no mission verdicts. */\n'+
 'export const MODEL_SOURCE_HASHES = '+JSON.stringify(hashes,null,2)+';\n'+
 'export const SERVED_CANDIDATES = '+JSON.stringify(pool,null,2)+';\n';
const outputs={'sim/served-candidates.js':body};
if(process.argv.includes('--emit'))console.log(JSON.stringify(outputs));
else if(process.argv.includes('--check')){
 const stale=Object.entries(outputs).filter(([f,v])=>!fs.existsSync(f)||fs.readFileSync(f,'utf8')!==v);
 if(stale.length){console.error('FAIL served candidates: '+stale.map(([f])=>f).join(', '));process.exitCode=1;}
 else console.log('PASS served candidates: record-derived controls and model source hashes are fresh');
}else{for(const [f,v] of Object.entries(outputs))fs.writeFileSync(f,v);console.log('Generated served candidate controls: '+Object.entries(pool).map(([id,p])=>id+'='+p.length).join(', '));}
