#!/usr/bin/env python3
"""Pure renderers for the notice gate. All per-file content comes from sidecars."""
from __future__ import annotations

from collections import Counter
import html
import re
from pathlib import PurePosixPath

INTRO = (
    "The fleet is simulated and never flew. The fire data is real; nothing here says a fire "
    "would have burned differently. Source code is licensed under Apache-2.0; third-party "
    "works retain the terms recorded below. The Information in the map layers was modified. "
    "No information provider endorses this project or its uses. For real emergencies use the official service."
)
ENERGY_NOTE = (
    "These energy figures come from the earlier flight model, which understates the force "
    "needed to hold an empty hull down. Corrected figures will be higher, and some cycles "
    "may not be flyable as drawn."
)
ENERGY_TAG = "earlier model · under review"
ENERGY_UNITS = re.compile(r"\b(?:MWh|kWh|MW|kW)\b")

DECISIONS = (
    "redistributed: included under the recorded terms; link-only: the public repository retains "
    "the source and hash, not the file; withheld: excluded pending author review; to-confirm: "
    "excluded until a person confirms the terms. Excluded records are an audit trail, not a "
    "redistribution notice or a claim of permission. The wind record describes an unbundled "
    "server service, not a repository file."
)


def ordered(recs: list[dict]) -> list[dict]:
    return sorted(recs, key=lambda r: (r['decision'] != 'to-confirm', r['path']))


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def md(value: object) -> str:
    return esc(value).replace('|', '&#124;').replace('\n', '<br>')


def sources(rec: dict) -> list[str]:
    value = rec['source']
    return value if isinstance(value, list) else [value]


def totals(recs: list[dict]) -> str:
    files = [r for r in recs if r.get('kind', 'file') == 'file']
    counts = Counter(r['decision'] for r in files)
    return (f"{len(files)} file records: " + ', '.join(f'{counts[d]} {d}' for d in
            ('redistributed', 'link-only', 'withheld', 'to-confirm')) +
            f". {len(recs) - len(files)} service record(s). Counts describe decisions, not files present in a release.")


def inventory(recs: list[dict]) -> str:
    lines = ['| Folder / file | Publisher | Licence / statement as recorded | Decision | Where the statement was read |',
             '|---|---|---|---|---|']
    for r in ordered(recs):
        lines.append('| ' + ' | '.join(md(v) for v in (
            r['path'], r['publisher'], r['licence'], r['decision'], r['licenceEvidence'])) + ' |')
    return '\n'.join(lines)


def measurements(r: dict) -> str:
    return ', '.join(f'{v:,} {k}' for k, v in r.get('measurements', {}).items()) or 'Not a bundled data measurement'


def detail(r: dict) -> str:
    fields = [('Decision', r['decision']), ('Publisher', r['publisher']),
              ('Licence', r['licence']), ('Licence statement', r['licenceStatement']),
              ('Statement evidence', r['licenceEvidence']), ('Terms address', r['licenceUrl']),
              ('Attribution', r['attribution']), ('Source', '\n'.join(sources(r))),
              ('SHA-256', r['sha256'] or 'Not applicable: unbundled service'),
              ('Decision reason', r['licenceReason']), ('Processing and caveats', r['notes']),
              ('Measured contents', measurements(r)), ('Record', r['sidecar'])]
    return '\n'.join(f'**{k}:** {md(v)}\n' for k, v in fields)


def markdown(recs: list[dict], title: str) -> str:
    return (f'# {title}\n\nGenerated by `python3 tools/noticecheck.py --write` from provenance sidecars. '
            'Do not edit by hand.\n\n' + INTRO + '\n\n' + DECISIONS + '\n\n' + totals(recs) +
            '\n\n## Per-file decisions\n\n' + inventory(recs) + '\n\n## Source records and credits\n\n' +
            '\n'.join(f'### {r["path"]}\n\n{detail(r)}' for r in ordered(recs)))


def page(recs: list[dict]) -> str:
    rows = []
    has_energy = False
    for r in ordered(recs):
        p = PurePosixPath(r['path'])
        fields = [('Attribution', r['attribution']), ('Statement', r['licenceStatement']),
                  ('Source', '\n'.join(sources(r))), ('SHA-256', r['sha256'] or 'Unbundled service'),
                  ('Reason', r['licenceReason']), ('Processing and caveats', r['notes']),
                  ('Measured contents', measurements(r)), ('Sidecar', r['sidecar'])]
        more = ''
        for k, v in fields:
            tag = ''
            if ENERGY_UNITS.search(str(v)):
                has_energy = True
                tag = (f'<small class="energy-tag">Model figures mentioned here: {ENERGY_TAG}. '
                       'Cited source measurements retain their cited basis.</small>')
            more += f'<dt>{esc(k)}</dt><dd>{esc(v)}{tag}</dd>'
        rows.append(f'<tr><th scope="row"><span class="folder">{esc(p.parent)}/</span>{esc(p.name)}</th>'
                    f'<td data-label="Publisher">{esc(r["publisher"])}</td>'
                    f'<td data-label="Licence"><span>{esc(r["licence"])}</span>'
                    f'<p class="evidence">Read at: {esc(r["licenceEvidence"])}</p>'
                    f'<a href="{esc(r["licenceUrl"])}">Terms reference</a>'
                    f'<details><summary>Credit and source record</summary><dl>{more}</dl></details></td>'
                    f'<td data-label="Decision"><strong>{esc(r["decision"])}</strong></td></tr>')
    energy_note = (
        '<aside><h2>Model energy comparisons</h2><p>Processing notes compare source '
        'measurements with model figures. The following notice applies to the model figures; '
        'source measurements retain their cited basis.</p>'
        f'<p data-energy-note>{ENERGY_NOTE}</p></aside>' if has_energy else '')
    return '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Data, licences and notices — Pink Robotics</title>
<style>
:root{color-scheme:dark;--bg:#101014;--text:#ded9cd;--muted:#b0aeb9;--warm:#ff75b4;--line:#42424c}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.55 system-ui,sans-serif}
main,header,footer{max-width:1240px;margin:auto;padding:24px}h1{font-size:clamp(30px,5vw,48px);line-height:1.15}
p{max-width:85ch}a{color:var(--warm);text-underline-offset:3px}table{width:100%;border-collapse:collapse;table-layout:fixed}
caption{text-align:left;font-weight:bold;padding:20px 0}th,td{vertical-align:top;text-align:left;padding:16px 12px;border-top:1px solid var(--line);overflow-wrap:anywhere}
th:nth-child(1){width:24%}th:nth-child(2){width:21%}th:nth-child(3){width:41%}th:nth-child(4){width:14%}
tbody th{font-weight:500}.folder{display:block;color:var(--muted)}.evidence{font-size:14px;color:var(--muted)}
details{margin-top:14px}summary{cursor:pointer;color:var(--warm)}dt{font-weight:600;margin-top:12px}dd{margin:0;white-space:pre-wrap}
footer{border-top:1px solid var(--line)}
.energy-tag{display:block;margin-top:8px;color:var(--muted);font-size:13px}
@media(max-width:900px){thead{position:absolute;clip-path:inset(50%);height:1px;width:1px;overflow:hidden}
caption{display:block;width:100%}table,tbody,tr,td,tbody th{display:block;width:100%!important}tr{padding:16px 0;border-top:1px solid var(--line)}
th,td{border:0;padding:8px 0}td[data-label]::before{content:attr(data-label);display:block;font-size:13px;color:var(--muted);font-weight:600}
main,header,footer{padding:20px}tbody th{font-size:18px}details{margin-top:12px}}
</style></head><body><header><a href="./">← Fleet monitor</a></header>
<main><h1>Data, licences and notices</h1>
''' + energy_note + f'<p>{esc(INTRO)}</p><p>{esc(DECISIONS)}</p><p>{esc(totals(recs))}</p>\n' + '''
<p>Generated from provenance sidecars. Read <a href="NOTICE">NOTICE</a>, <a href="DATA-SOURCES.md">DATA-SOURCES.md</a> and the <a href="LICENSE">code licence</a>. Repository paths below are references, not links to files served by this website.</p>
<table><caption>Per-file decisions — unresolved terms first</caption><thead><tr><th scope="col">Folder / file</th><th scope="col">Publisher</th><th scope="col">Licence and evidence</th><th scope="col">Decision</th></tr></thead><tbody>
''' + '\n'.join(rows) + '''
</tbody></table></main><footer><a href="./">Fleet monitor</a> · <a href="notices.html">Data, licences and notices</a> · <a href="LICENSE">Code licence</a></footer></body></html>
'''


def data_readme(recs: list[dict]) -> str:
    data = [r for r in recs if r['path'].startswith('data/') and r.get('kind', 'file') == 'file'
            and r['decision'] == 'redistributed']
    lines = ['# data', '', 'Generated by `python3 tools/noticecheck.py --write` from verified sidecar measurements.', '',
             f'{len(data)} bundled data files. Runtime mirrors under `data/live/` are unbundled; their README explains them.', '',
             'The fire data is real. The fleet is simulated and never flew. Credits, source addresses and processing',
             'are in [DATA-SOURCES.md](../DATA-SOURCES.md) and [NOTICE](../NOTICE).', '',
             'Recompute every current count without network access: `python3 tools/noticecheck.py --counts`.', '',
             '| File | Bytes | Measured contents | Generator |', '|---|---:|---|---|']
    for r in data:
        m = r['measurements']
        counts = ', '.join(f'{v:,} {k}' for k, v in m.items() if k != 'bytes') or 'See source record'
        lines.append(f'| `{PurePosixPath(r["path"]).relative_to("data")}` | {m["bytes"]:,} | {counts} | {md(r.get("generator") or "Pinned capture; no generator")} |')
    lines += ['', '## Count correction', '',
              'The earlier README said six files; it omitted the historical-fire dataset. It also described the',
              'pre-regeneration Natural Earth vectors: 294 road polylines / 3,032 vertices and 23 outline rings /',
              '804 vertices. Those historical values are retained here as the old values, not current measurements.',
              'The table above is measured from the current files. `pipeline/vectors.py` now reproduces the vectors',
              'from the pinned Natural Earth archive recorded in their sidecars. The notice repair changes no geometry.', '',
              'Snapshot files are pinned test inputs. Re-fetching them changes the replay. This notice generator only',
              'reads local bytes; it never calls an agency feed. Surface area is a proxy for water access, and simplified',
              'historical perimeters are not operational fire lines. Providers do not endorse this project.', '']
    return '\n'.join(lines)


def outputs(recs: list[dict]) -> dict[str, str]:
    generated = {'NOTICE': markdown(recs, 'Third-party notices'),
            'DATA-SOURCES.md': markdown(recs, 'Data sources, licences and attribution'),
            'notices.html': page(recs), 'data/README.md': data_readme(recs)}

    # Preserve source-specific methodology and measured tables in the source record.
    for r in sorted(recs, key=lambda item: (item['path'].endswith('.evac.json'), item['path'].endswith('.guard.json'), item['path'])):
        for name, content in r.get('documentation', {}).items():
            if name in generated:
                generated[name] += '\n' + content
    return generated
